### ISSUE TITLE
Attention à l'invalidité

### ISSUE THREAD

**Issue by Poussinou** [AdrienPoupa/AttestationDeplacement#1]
Bonjour,

J'ai vu ta MR sur le dépot de F-Droid.

Il me semble que les attestations papier ne sont pas/plus acceptées, selon [cet article](https://www.liberation.fr/checknews/2020/03/18/confinement-peut-on-montrer-l-attestation-de-deplacement-sur-son-telephone_1782180), [cet article](https://www.ouest-france.fr/sante/virus/coronavirus/coronavirus-pour-les-sorties-justifiees-finalement-seule-une-attestation-sur-papier-est-valable-6784636), ou ce [tweet](https://twitter.com/Place_Beauvau/status/1240236276416118784) du ministère.

Il est peut être préférable de ne pas diffuser l'appli, pour éviter que des gens soient exposés à des amendes alors que c'était évitable, et remplissent un vrai papier.

**Comment by AdrienPoupa** [comment]
Salut,

J'ai vu ça, je m'étais dit que cela restait possible de générer le PDF et de l'imprimer. Je vais ajouter un texte explicatif dans l'application.

Il est également possible de voir une volte face quant à la validité des attestations mobiles, vu la vitesse à laquelle vont les choses.

**Comment by Poussinou** [comment]
Je ne suis pas sûr que les gens, après l'avoir complété sur le portable, vont aller l'imprimer ou le transférer sur le PC pour l'imprimer pour être honnête.

Après je suis d'accord que les choses vont peut être changer, ou pas, on ne sait pas encore... Un énorme avertissement me semble en effet être indispensable. L'idée derrière l'appli est pas mal ceci dit 👍

**Comment by AdrienPoupa** [comment]
Merci, je m'en occupe dès que possible et je mettrai à jour la MR de F-Droid.

**Comment by AdrienPoupa** [comment]
J'ai maj l'appli en conséquence:

![Screenshot_20200319-233222_Attestation_Coronavirus](https://user-images.githubusercontent.com/15086425/77134652-5da78e00-6a3e-11ea-9676-3a5e4ed3103a.png)
![Screenshot_20200319-233209_Attestation_Coronavirus](https://user-images.githubusercontent.com/15086425/77134653-5e402480-6a3e-11ea-9ffd-37366214b20b.png)

**Comment by Poussinou** [comment]
Ça me semble honnête. Pour te couvrir toi même j'aurai aussi mis un mot comme quoi l'auteur décline toute responsabilité en cas de contrôle et de non acceptation de l'attestation présentée sur le portable via cette appli, un truc dans ce genre... Ça coute pas cher mais ça peut t'éviter des problèmes :)
