### ISSUE TITLE
Date de naissance décalée d'un mois

### ISSUE THREAD

**Issue by awerner25** [AdrienPoupa/AttestationDeplacement#10]
Bonjour,

Lorsque je selectionne ma date de naissance (30/11/1987), il remplit l'input avec "30 octobre 1987".

**Comment by AdrienPoupa** [comment]
Salut,

La dernière version, 1.0.2 (pas encore sur F-Droid) résout le problème. Tu peux désinstaller la version actuelle et récupérer l'APK ici si tu ne veux pas attendre: https://github.com/AdrienPoupa/AttestationCoronavirus/releases/download/1.0.2/app-release.apk

**Comment by awerner25** [comment]
Merci.
