### ISSUE TITLE
Format données QR code inexact

### ISSUE THREAD

**Issue by luffah** [AdrienPoupa/AttestationDeplacement#100]
(Bonjour)

Quand je récupère un QR Code d'une attestestion généré depuis le site du gouvernement et je compare le QR code il y a une différence pas bien flagrante sur les formats de données: il manque un point-virgule et un retour ligne à la fin des données.
**officiel** 
```
...
Motifs: achats;

scanned 1 barcode symbols from 1 images in 0.03 seconds
```

**par l'appli**
```
...
 Motifs: achats
scanned 1 barcode symbols from 1 images in 0.04 seconds
```

**Comment by okpapt** [comment]
Il me semble qu'il est possible de recopier manuellement le formulaire.
Si tu as le temps, tu peux donc aussi dessiner le qrcode... (il ne sera donc pas identique au pixel)
:-))
Sauf erreur de ma part :
-    il n'y a aucune obligation d'utiliser l'application officielle.
-    il n'y a aucune interdiction d'utiliser une application tierce.
Alors s'il y a un caractère non gênant et non indispensable en trop ou en moins, est-ce si grave ?

**Comment by luffah** [comment]
Je signal seulement un petit bug sans gravité.

**Comment by AdrienPoupa** [comment]
Merci du rapport, c'est corrigé.
