### ISSUE TITLE
La nouvelle attestation sera-t-elle dispo?

### ISSUE THREAD

**Issue by Blovario** [AdrienPoupa/AttestationDeplacement#101]
Salut, je pense que tout est dans le titre :')
L'attestation a changé et est-ce qu'il sera dispo?

Merci!

Edit: bon je viens de voir que cette question a déjà été posée... Ne prenez pas en compte cette demande du coup! Et merci aux contributeurs !

**Comment by luffah** [comment]
Voir #98

Vous pouvez clore vous même ce ticket. Le mainteneur de l'appli à l'air pas mal occupé.
