### ISSUE TITLE
Ajouter la possibilité de générer une attestation de manifestation

### ISSUE THREAD

**Issue by N07070** [AdrienPoupa/AttestationDeplacement#103]
Bonjour,

Je me rend compte qu'il n'est pas possible de générer une attestation pour se rendre en ~émeute~ manifestation, comme celle de la Ligue des Droits de l'Homme : https://www.ldh-france.org/wp-content/uploads/2020/11/Attestation-de-d%C3%A9placement-d%C3%A9rogatoire-pour-manifester.25.11.2020.pdf

Serait-il possible de la rajouter ? 

Merci :)

**Comment by AdrienPoupa** [comment]
Bonjour,
Je préfère garder le modèle officiel, libre a vous d'en utiliser un autre.
