### ISSUE TITLE
Soucis à l'ouverture du fichier généré

### ISSUE THREAD

**Issue by Joe084** [AdrienPoupa/AttestationDeplacement#11]
Bonjour,
Tout d'abord merci pour cette solution qui permet une utilisation sans réseau :)
J'ai un souci une fois le fichier généré, à l'ouverture avec muPDF mini j'ai le message suivant : 
`magic must not be null`
Avec l'application PDF de Google, elle s'ouvre bien.. Cela vient de l'application ou du lecteur PDF utilisé ?
Bien à vous,
Joe

**Comment by AdrienPoupa** [comment]
Je me sers du lecteur de base et pas de problème particulier à déplorer, je ne connais pas muPDF donc aucune idée :/

Peut-être a voir avec les maintainers de muPDF?

**Comment by AdrienPoupa** [comment]
Apparemment ca vient d'ici: https://github.com/ccxvii/mupdf/blob/master/platform/java/mupdf_native.c#L4430 mais je ne saurais pas dire ce qui le cause

**Comment by AdrienPoupa** [comment]
De plus j'arrive a l'ouvrir sans problème avec Okular et le lecteur de PDF de Firefox et Chrome, donc je pense que ça vient plus de muPDF, désolé

**Comment by Joe084** [comment]
Merci du retour,
enfait muPDF arrive à ouvrir le fichier généré quand je vais dans la mémoire interne / documents / attestations, mais n'arrive pas à l'ouvrir via l'application. Je verrai comment cela évolue avec les prochaines versions.
Cette application mériterait d'être l'officielle pour le coup.
