### ISSUE TITLE
Et merde !

### ISSUE THREAD

**Issue by bepolymathe** [AdrienPoupa/AttestationDeplacement#116]
Bon ben Adrien... c’est le retour des attestations (pour certains en tout cas) !
L’occasion de te remercier de nouveau pour cet outil dont on va malheureusement avoir encore besoin.
Courage à tous.

**Comment by Iey4iej3** [comment]
https://www.service-public.fr/particuliers/vosdroits/R57404

J'espère que cela sera le dernier confinement. Peut-être nous devons aussi une attestation de vaccination après...

**Comment by Dubs120** [comment]
Bonjour, le lien montre que même le site officiel n'arrive plus à suivre les mises-à-jour de notre gouvernement.
Si cela devait - et cela semble le cas - s'inscrire dans la durée, peut-être serait-il une bonne idée de laisser le canevas accessible sans devoir systématiquement tout recompiler, non?

**Comment by AdrienPoupa** [comment]
Je vais regarder merci!

**Comment by AdrienPoupa** [comment]
C'est bon :)
