### ISSUE TITLE
Choisir la langue ?

### ISSUE THREAD

**Issue by Shohreh** [AdrienPoupa/AttestationDeplacement#117]
Bonjour,

Comme mon téléphone Android est installé en anglais, c'est la langue qu'utilise l'appli pour s'afficher.

Le PDF est bien en français, mais je demandais s'il y avait un moyen de changer la langue. Je n'ai rien trouvé dans le menu.

Merci.

**Comment by AdrienPoupa** [comment]
Bonjour,

Cela fonctionne comme attendu. Pour la plupart des applications, la langue se base sur celle du téléphone.
