### ISSUE TITLE
Ajout des nouveaux motifs et utilisation de la nouvelle template :(

### ISSUE THREAD

**Issue by lefuturiste** [AdrienPoupa/AttestationDeplacement#119]
Une nouvelle version vient de sortir (qui fait deux pages) :

https://www.service-public.fr/particuliers/vosdroits/R57403

https://www.interieur.gouv.fr/content/download/126752/1013433/file/19-03-2021-attestation-de-deplacement-derogatoire.pdf#xtor=AD-322

**Comment by AdrienPoupa** [comment]
Je vais regarder merci!

**Comment by ortolot** [comment]
En fait le contexte a changé, il y a maintenant, selon les endroits :
* une attestation pour sortir après le couvre-feu ;
* une attestation pour sortir, hors couvre-feu, dans les départements soumis à un confinement local.

Il faudrait donc gérer un choix entre ces deux contextes…

**Comment by AdrienPoupa** [comment]
Effectivement, merci. On va utiliser #116 pour tracker tout ça.
