### ISSUE TITLE
Contenu du QR Code erroné 

### ISSUE THREAD

**Issue by grrosminet** [AdrienPoupa/AttestationDeplacement#12]
Belle initiative, mais le contenu du QR Code ne correspond pas à ce que génère le site du gouvernement
- il manque l'heure de sortie 
- l'heure de création est sur 12h sans préciser AM/PM (devrait être sur 24h)
- le motif de déplacement n'est pas correct (devrait être "sport" au lieu de "bref")

**Comment by AdrienPoupa** [comment]
Bonjour,

La version 1.0.2 corrige ca, mais F-Droid est lent a build: https://github.com/AdrienPoupa/AttestationCoronavirus/releases/download/1.0.2/app-release.apk
