### ISSUE TITLE
Impossible de créer un nouveau profil

### ISSUE THREAD

**Issue by Altonss** [AdrienPoupa/AttestationDeplacement#120]
J'utilise l'application dans sa version 3.5.1 provenant de F-Droid sous Android 5.0.1 et il m'est impossible de créer un nouveau profil. Quand je clique sur le bouton + alors même que je suis dans l'onglet profils, cela m'ouvre l'interface pour créer une nouvelle attestation.

Encore merci beaucoup pour cette application libre qui fonctionne très bien et m'est très utile au quotidien !

**Comment by AdrienPoupa** [comment]
Bonjour,

Le profil se crée au moment de la création de l'attestation.

**Comment by Altonss** [comment]
Je viens de comprendre, merci pour l'explication!
