### ISSUE TITLE
Version 3.6.0

### ISSUE THREAD

**Issue by trev0r-STA** [AdrienPoupa/AttestationDeplacement#123]
Bonsoir. 

Il est où l'apk??
Chouette boulot, sinon. Merci de ns aider en ces temps difficiles (ns font c***r avec leur foutus paperasses)

**Comment by AdrienPoupa** [comment]
Bien vu, il y avait eu un souci pendant l'envoi. Il est ici: https://github.com/AdrienPoupa/AttestationDeplacement/releases/download/3.6.0/app-release.apk

Et sur le Play Store des que possible.
