### ISSUE TITLE
Nouvelle version de l'attestation

### ISSUE THREAD

**Issue by Gyom14** [AdrienPoupa/AttestationDeplacement#124]
Bonjour,
Une nouvelle version de l'attestation pdf est disponible
https://www.interieur.gouv.fr/content/download/126923/1014779/file/03-04-2021-attestation-de-deplacement-derogatoire.pdf

**Comment by AdrienPoupa** [comment]
Merci, je vais regarder ! (ils ne s'arrêtent jamais)

**Comment by AdrienPoupa** [comment]
https://github.com/AdrienPoupa/AttestationDeplacement/releases/tag/3.7.0 :)
