### ISSUE TITLE
Thème sombre

### ISSUE THREAD

**Issue by trev0r-STA** [AdrienPoupa/AttestationDeplacement#125]
Bonjour

Un thème sombre est envisageable ?
Çà pique un peu les yeux à 4h du mat' dans la voiture quand tu génères ton attestation :-)

Sinon appli toujours aussi agréable

Merci

**Comment by AdrienPoupa** [comment]
Salut,

Il y a déjà un thème sombre, actif quand ton téléphone est en mode sombre également.
