### ISSUE TITLE
Impossible de créer plusieurs profils sur 3.6.0

### ISSUE THREAD

**Issue by Valeryan24** [AdrienPoupa/AttestationDeplacement#127]
Bonjour,

J'ai téléchargé l'apk le plus récent sur Github et installé par-dessus la dernière version que j'avais (datant de décembre 2020).

Je retrouve bien mon profil et les nouvelles attestations, par contre impossible de créer un second profil : 

- lorsque je suis sur l'onglet Profils et clique sur "+", cela ne me propose pas de créer un profil à aprtir des infos du 1er, mais de générer une attestation.

- si je change des informations (ex l'adresse) et génère l'attestation, puis retourne sur Profils, les nouvelles infos ont remplacé les anciennes dans le profil au lieu d'en créer un autre ou de juste les utiliser pour cette attestation…

Ce n'est pas très grave, j'ai testé cela car je vais switcher cette semaine entre mes deux appartements pour le travail, et ce n'est peut-être pas prévu pour ce genre de cas - ou alors il faudrait que j'efface cache + données ?

Version 3.6.0 sur Android 11, Samsung Galaxy S10+

En tout cas encore merci pour cette super appli.

**Comment by MaximeChretien** [comment]
Salut, 
Si je ne dit pas de bêtises, les profils se basent sur le nom uniquement pour les différencier.

Ce que je fais pour avoir plusieurs profils c'est que j'ajoute un espace après mon prénom quand je crée le second profil, c'est invisible mais l'appli considère que c'est deux profils différents.

J'espère que cette technique résoudra ton problème !
