### ISSUE TITLE
v3. 7.0 La création de profils ne fonctionne plus 

### ISSUE THREAD

**Issue by clavelm** [AdrienPoupa/AttestationDeplacement#128]
Bonjour,
Je viens d'essayer de créer un profil avec la version 3.7.0 et ce n'est plus possible. Je ne sais pas depuis quelle version il y a ce problème. 
Ayant créé mon profil sur une version précédente, je ne me souviens plus de la procédure exacte.
Dans l'onglet profils, le bouton + lance la création d'une attestation, comme dans l'onglet attestations.
J'ai essayé de supprimer les données, puis de désinstaller/réinstaller, il n'est plus possible de créer un profil.
(Heureusement j'ai une sauvegarde titanium pour remettre mon profil et pouvoir utiliser l'application uniquement pour moi en attendant).

Téléphone : oneplus 9 pro / OxygenOS Android 11

**Comment by AdrienPoupa** [comment]
Bonjour,

Un profil se crée automatiquement basé sur le nom et prénom lors de la création de l'attestation.

**Comment by clavelm** [comment]
Ah oui, forcément, ça marche mieux comme ça 😅. 
Merci pour ta super application bien pratique.
