### ISSUE TITLE
Date de naissance

### ISSUE THREAD

**Issue by hista** [AdrienPoupa/AttestationDeplacement#13]
Bonjour,
comment faire pour rentrer efficacement sa date de naissance, plutôt qu'en cliquant pour remonter de mois en mois en arrière depuis avril 2020, ce qui peut durer longtemps quand on n'est pas un perdreau de l'année ? :-)

**Comment by AdrienPoupa** [comment]
Salut,

La dernière version, 1.0.2 (pas encore sur F-Droid) résout le problème en proposant de saisir l'année en premier. Tu peux désinstaller la version actuelle et récupérer l'APK ici si tu ne veux pas attendre: https://github.com/AdrienPoupa/AttestationCoronavirus/releases/download/1.0.2/app-release.apk
