### ISSUE TITLE
Impossible d'ouvrir le PDF - Android 6.0

### ISSUE THREAD

**Issue by ghost** [AdrienPoupa/AttestationDeplacement#14]
Bonjour,
Sur mon smartphone Honor 7 avec Android 6.0 avec la version 1.1.0 de l'application, je n'arrive pas à ouvrir le pdf, voici l'erreur que cela produit :
![Screenshot_2020-04-10-09-02-46](https://user-images.githubusercontent.com/63443177/78972193-7a9b2280-7b0d-11ea-8155-0e3fc6fcbe66.png)

Et je n'ai pas l'autorisation système pour ouvrir le dossier /data/... pour vérifier si le fichier y est bien présent.

Si je fait un appui long sur le nom du fichier et partage par courriel cela ouvre un message sans pièce jointe.

**Comment by chcolin** [comment]
J'ai aussi eu un refus d'ouverture avec MuPDF, mais en changeant d'appli aucun problème.
Btw, dommage que le QRCode n'y figure pas contrairement au PDF généré par l'appli officielle.

**Comment by AdrienPoupa** [comment]
La version 1.1.0 génère un PDF identique a l'officielle avec les deux qr code, mais F Droid est vraiment très long a build...

https://github.com/AdrienPoupa/AttestationCoronavirus/releases/download/1.1.0/app-release.apk

**Comment by chcolin** [comment]
Effectivement, la 1.0.0 n'est toujours pas en ligne... Nette amélioration, bravo pour le nouveau PDF !
Juste un détail à améliorer, à la lecture des QR codes, la date de naissance est en ././. sur l'officiel et non en texte.

**Comment by AdrienPoupa** [comment]
@chcolin bien vu ! Une nouvelle version qui corrige ceci sort bientôt

**Comment by AdrienPoupa** [comment]
@chcolin Réglé en 1.2.1 :) J'ai désormais changé le calendrier en champ classique JJ/MM/AAAA

https://github.com/AdrienPoupa/AttestationDeplacement/releases/download/1.2.1/app-release.apk

L'application est désormais aussi disponible sur le Play Store: https://play.google.com/store/apps/details?id=com.poupa.attestationdeplacement

**Comment by chcolin** [comment]
L'appli s'installe bien via le Play Store, mais l'installation de la 1.2.1 via github est bloquée par Play Protect (développeur inconnu). Ce n'était pas le cas avec la 1.1.0

**Comment by Nico207** [comment]
Il reste effectivement un problème à l'ouverture du PDF, même avec la dernière version.
Mais ce problème dépend du lecteur utilisé et non de cette application.

- [MuPDF Viewer](https://mupdf.com/) → _Erreur_
- [Cuprum PDF](https://github.com/paride/CopperPDF) → _Erreur_
- [Pdf Viewer Plus](https://github.com/JavaCafe01/PdfViewer) → **OK**
- [Librera PRO](https://github.com/foobnix/LibreraReader) → **OK**

**Comment by AdrienPoupa** [comment]
@chcolin probablement car l'application est maintenant sur le Play Store, donc ce doit être une protection pour empêcher l'installation d'applis malveillantes (= même nom que Play Store mais clé différente)

@Nico207 la façon dont j'ouvre le PDF est vraiment très classique: https://github.com/AdrienPoupa/AttestationDeplacement/blob/master/app/src/main/java/com/poupa/attestationdeplacement/AttestationAdapter.java#L132

J'essaierai de voir pourquoi cela ne fonctionne pas mais je suis étonné

**Comment by Nico207** [comment]
Je ne pense pas qu'il faille perde du temps là-dessus, car la demande d'ouverture me semble bonne.
Du coup, je pense que le problème provient plutôt de la façon dont les applications de lecture réceptionnent cette demande.

**Comment by chcolin** [comment]
@AdrienPoupa Probablement, de toute façon cela n'empêche pas d'installer l'apk, et une fois fait Play Protect ne détecte plus de problème.

**Comment by ghost** [comment]
> Il reste effectivement un problème à l'ouverture du PDF, même avec la dernière version.
> Mais ce problème dépend du lecteur utilisé et non de cette application.
> 
>     * [MuPDF Viewer](https://mupdf.com/) → _Erreur_
> 
>     * [Cuprum PDF](https://github.com/paride/CopperPDF) → _Erreur_
> 
>     * [Pdf Viewer Plus](https://github.com/JavaCafe01/PdfViewer) → **OK**
> 
>     * [Librera PRO](https://github.com/foobnix/LibreraReader) → **OK**

Je viens d'installer Pdf Viewer Plus et forcer l'ouverture par défaut des PDF avec.
Et bien votre appli continu à ouvrir le PDF avec Document Viewer et plante.
Je supprime Document Viewer et votre appli donne "Open File aucune application ne peut effectuer cette action." quand on clique sur [PDF] :'(

**Comment by ghost** [comment]
Ce serait pas possible et plus simple de générer le fichier plutot dans le dossier Download ?

**Comment by Nico207** [comment]
@El-Tacos 
L'application d'AdrienPoupa indique simplement à Android qu'un fichier de type PDF doit être ouvert.
Par la suite, Android devrait vous proposer l'ensemble des applications capable d'ouvrir ce type de fichier. Si ce n'est pas le cas, c'est qu'un problème a dû survenir lors de l'installation de PDF Viewer ou lors de la désinstallation de Document Viewer.
Dans un premier temps, avez-vous essayé de redémarrer votre appareil ?

**Comment by ghost** [comment]
Oui, redémarrer ne change rien.
D'autres applications ouvre les pdf directement avez l'appli par défaut sans soucis.

**Comment by Nico207** [comment]
Étrange... 🤔 
Le mieux serait de désinstaller les deux applications (PDF Viewer Plus et AttestationDeplacement) puis de les réinstaller.

**Comment by ghost** [comment]
Je viens de le faire, mais ça ne change rien :(

**Comment by chcolin** [comment]
@El-Tacos C'est que Document Viewer est défini en application par défaut pour la lecture des PDF.
Pour corriger cela, allez dans Paramètres/Applications puis recherchez Document Viewer dans la barre de recherche.
Une fois la "fiche" de l'appli ouverte, allez tout en bas et annulez l'application par défaut.

**Comment by ghost** [comment]
Sauf que comme je l'ai dit la : https://github.com/AdrienPoupa/AttestationDeplacement/issues/14#issuecomment-613992998
J'ai supprimé Document Viewer et il n'y a plus qu'une seule application capable d'ouvrir les PDF.
J'ai tout supprimé vider les caches, installé dabord PDF viewer plus puis Attestation de déplacement mais elle n'arrive toujours pas à trouver l'appli pour ouvrir le PDF.
Et mes autres appli (mail, traceur GPS, file explorer) y arrive.

**Comment by AdrienPoupa** [comment]
J'ai testé toutes les applis sur la version 1.3.0 et ca fonctionne sur Android 10

**Comment by Nico207** [comment]
Je confirme : l'ouverture se fait bien sur toutes les applications indiquées.
Merci !

**Comment by ghost** [comment]
Génial, avec la 1.4.1 ça fonctionne enfin sur mon smartphone !
Merci.
