### ISSUE TITLE
Ne marche tout simplement pas ;-(

### ISSUE THREAD

**Issue by manatlan** [AdrienPoupa/AttestationDeplacement#15]
L'idée est bonne ....
Je viens de l'installer (android10)
Mais quand je clique sur "générer", il m'affiche un toaster "erreur", comme ci-dessous :
![image](https://user-images.githubusercontent.com/150722/78981548-6dd3fa00-7b20-11ea-9bb1-f31b917d5d63.png)

Il y a un truc que j'ai loupé ?

**Comment by AdrienPoupa** [comment]
Salut, est-ce que tu peux faire un logcat? Ça fonctionne chez moi avec Android 9 mais je sais qu'il y a eu des modifications du stockage pour la 10

**Comment by manatlan** [comment]
J'ai fait du dev android ... j'eusse su le faire ...
mais je ne me rappelle plus ;-)
si tu peux me guider ... je veux bien
(j'ai quand même du adb fonctionnel, avec la cnx usb qui fonctionne sous mon ubu)

**Comment by AdrienPoupa** [comment]
Je viens d'installer l'appli sur un virtual device Android 10 tout neuf et ça fonctionne sans souci :(

Tu devrais pouvoir voir le souci avec un adb logcat effectivement

Tu as bien la 1.1.0?

**Comment by myroad94** [comment]
Bonjour, j'avais aussi cette erreur sur Android 9, car je n'avais pas accepté la permission du stockage. Après avoir accepté l'appli fonctionne.

**Comment by AdrienPoupa** [comment]
La version 1.1.0 utilise le stockage interne donc normalement pas besoin d'accepter quoique ce soit

**Comment by myroad94** [comment]
> La version 1.1.0 utilise le stockage interne donc normalement pas besoin d'accepter quoique ce soit

Sans doute alors car la dernière version disponible sur fdroid est la 0.0.4 :)

**Comment by gerbier** [comment]
bonjour
je suis sur lineageos 17.1, ce qui correspond à android 10, et j'ai le même souci avec la version 0.04 de fdroid.
dans les autorisations, je ne vois que 'stockage' (acceptée)
et avec logcat, j'ai l'erreur suivante 
04-11 18:02:50.573 11717 11717 W System.err: java.io.FileNotFoundException: /storage/emulated/0/Documents/Attestations/Attestation-2020-04-11-18-02.pdf: open failed: EACCES (Permission denied)

ps : sur un android 8, l'application marche parfaitement?

**Comment by gerbier** [comment]
et je confirme qu'avec la version 1.1.0 téléchargée sur github, ça marche aussi sur android 10

**Comment by AdrienPoupa** [comment]
Je me permets de fermer car la 1.1.0 devrait résoudre le problème, tu peux fermer si c'est pas le cas

**Comment by manatlan** [comment]
et elle se télécharge où cette fameuse 1.1.0 ?
(pk je ne me vois pas télécharger les sources et les builder moi meme ;-)

**Comment by AdrienPoupa** [comment]
Oups je pensais avoir mis le lien!

https://github.com/AdrienPoupa/AttestationCoronavirus/releases/download/1.1.0/app-release.apk

**Comment by manatlan** [comment]
Merci beaucoup ...
Cette version marche parfaitement




Le dim. 12 avr. 2020 à 00:14, Adrien Poupa <notifications@github.com> a
écrit :
