### ISSUE TITLE
La saisie de la date de naissance est impossible : à 60 ans cela implique 720 fois mois précédent !

### ISSUE THREAD

**Issue by procrastin** [AdrienPoupa/AttestationDeplacement#16]
Cela rend la saisie pratiquement inutilisable. Il  faut admettre une saisie directe ou assistée jour, puis mois, puis année. 
Dommage !

**Comment by procrastin** [comment]
Sur Moto 3G, Lineage OS 14.1 officielle.

**Comment by vince2bir** [comment]
Vous pouvez cliquer sur l'année en haut de la fenêtre de sélection.

**Comment by procrastin** [comment]
Effectivement, merci du renseignement. 
Mais je pense que ce n'est pas facile à deviner. Peut-être est-ce habituel pour des saisies de date sous Androïd mais je n'étais pas au courant. Je pense qu'un petit symbole, flèche en haut " ^ " à coté de l'année (comme flèche à gauche " < " est à côté du mois en cours) permettrait de deviner plus aisément que l'année est modifiable.

**Comment by vince2bir** [comment]
Oui, très juste. Le pavé numérique est très bien aussi pour rentrer 6 chiffres :)

**Comment by AdrienPoupa** [comment]
La version 1.1.0 commence par vous inviter a saisir l'année https://github.com/AdrienPoupa/AttestationCoronavirus/releases/download/1.1.0/app-release.apk

**Comment by procrastin** [comment]
Mais F-Droïd ne propose toujours que la version 0.0.4 qui ne daterait que de 5 jours paraît-il...

Merci en tout cas.

**Comment by AdrienPoupa** [comment]
J'ai vu que F Droid a build la 1.1.0 hier, ils devraient mettre a jour leur repo aujourd'hui normalement

**Comment by procrastin** [comment]
Parfait ;-)
Merci.

**Comment by AdrienPoupa** [comment]
Réglé en 1.2.1 :) J'ai désormais changé le calendrier en champ classique JJ/MM/AAAA

https://github.com/AdrienPoupa/AttestationDeplacement/releases/download/1.2.1/app-release.apk

L'application est désormais aussi disponible sur le Play Store: https://play.google.com/store/apps/details?id=com.poupa.attestationdeplacement
