### ISSUE TITLE
Heure de sortie

### ISSUE THREAD

**Issue by zorzibaffo** [AdrienPoupa/AttestationDeplacement#17]
Bonjour,

Merci pour cette appli très précieuse et pratique.

En revanche, il ne semble pas possible de faire figurer l'heure de sortie (pourtant obligatoire en France, surtout pour le motif "activité physique").

Cette fonctionnalité pourrait-elle être ajoutée ?

Merci.

**Comment by chcolin** [comment]
Je pense que vous n'avez pas téléchargé la dernière version mais celle obsolète qu'affiche encore F-Droid.
La dernière release est la 1.2.1 =>https://github.com/AdrienPoupa/AttestationDeplacement/releases

**Comment by zorzibaffo** [comment]
Ah oui, en effet. Je vais récupérer la dernière version, ou bien attendre que la mise-à-jour arrive dans fdroid.
Merci encore.

**Comment by okpapt** [comment]
@zorzibaffo 
Il vaut mieux prendre directement sur github, car f-droid est un peu à la traine, et de plus il y a l'historique des release.

**Comment by zorzibaffo** [comment]
Entendu. Merci.

**Comment by Joe084** [comment]
Bonjour,
J'ai le souci également avec la v1.2.1 github. Je suis sur android 8
Bien à vous

**Comment by zorzibaffo** [comment]
> Bonjour,
> J'ai le souci également avec la v1.2.1 github. Je suis sur android 8
> Bien à vous

Je pense que l'heure est intégrée automatiquement au moment de la génération de l'attestation (même s'il ne faut pas la renseigner spécifiquement).
