### ISSUE TITLE
suggestions attestation

### ISSUE THREAD

**Issue by okpapt** [AdrienPoupa/AttestationDeplacement#18]
Bonjour et merci pour l'appli.

Merci de bien vouloir :
permuter le bouton générer et les coordonnées, afin qu'il soit tout en haut
laisser le motif des sorties au milieu (dès jeudi : adopter un animal spa)
dans les coordonnées tout en bas, ajouter après adresse les champs code postal et ville
afficher directement en plus grand le qrcode sur fond opaque et mettre en arrière plan l'application

Je suggère aussi de pouvoir modifier automatiquement les informations de création et de sortie à un moment antérieur à la réalité de création, afin que ce soit crédible auprès des forces de l'ordre en cas de génération juste avant un contrôle. (actuellement dans les paramètres, je retarde de 30 minutes l'heure du smartphone à chaque sortie).

Merci encore pour votre travail.

**Comment by AdrienPoupa** [comment]
La nouvelle version permet de modifier la date et l'heure de sortie
