### ISSUE TITLE
suggestions 2

### ISSUE THREAD

**Issue by okpapt** [AdrienPoupa/AttestationDeplacement#20]
Bonjour,

Pour une question de rapidité de manipulations, hier j'ai maladroitement fait qq propositions en classant de haut en bas du plus utilisé/modifié au moins.

Les coordonnées, on ne les saisit qu'une fois, sauf à chaque mise à jour (et c'est bien dommage).
Merci de bien vouloir ajouter les champs code postal et ville (la première fois je n'ai mis que la ville car le champs est petit).

Le motif de sortie change moins souvent, mais c'est un peu long de tout lire. Aussi je propose de ne cocher que le mot figurant sur l'attestation, avec à côté un ? qui affiche le texte complet en cliquant dessus.

Entre le motif et les coordonnées, un champs (ou deux) pour différer d'un moment la date/heure de création et début de sortie.

Afficher plus grand et sur fond opaque le qrcode, tout en mettant l'application en arrière plan.

En espérant que cette proposition sera lue, comprise et retenue pour une intégration prochaineùent.
Bonne continuation.
Dominique.

**Comment by chcolin** [comment]
Bonjour, 
Personnellement, l'appli d'Adrien me convient très bien telle quelle, mais bon...
PS : Les suggestions relèvent de Pull requests et non Issues

**Comment by okpapt** [comment]
désolé, je découvre github.

J'utilise le site du gouvernement en partant de chez moi.
La version officielle n'a jamais la même heure entre celle de création et celle de la sortie.
L'appli oui, à la minute près., Ca pourrait surprendre les forces de l'ordre, surtout les pointilleux. Si si, ça existe.

PS: je viens d'aller voir et je ne comprends pas comment  ça fonctionne, si vous voulez bien y faire un copier/coller de mon message, je vous en remercie d'avance.

**Comment by okpapt** [comment]
En fait je n'ai que suivre le lien proposé sur la page principale :
https://github.com/AdrienPoupa/AttestationDeplacement

"Si tu es sûr d'avoir la dernière version et que le problème est toujours présent tu peux ouvrir un ticket"

**Comment by Nico207** [comment]
@okpapt Vous avez très bien fait, les suggestions se font effectivement plutôt dans cette section. La section des Pull Requests est plutôt réservée aux développeurs, pour proposer une fonctionnalité **déjà codée**.

**Comment by okpapt** [comment]
@Nico207 Merci, Il ne reste plus qu'à espérer que ça sera dans la prochaine version, jeudi normalement avec l'adoption des animaux, surtout que ce n'est pas une trop grande modification(il me semble).

**Comment by chcolin** [comment]
> 
> 
> @okpapt Vous avez très bien fait, les suggestions se font effectivement plutôt dans cette section. La section des Pull Requests est plutôt réservée aux développeurs, pour proposer une fonctionnalité **déjà codée**.


Oui et non. 
Idéalement, oui c'est pensé pour aider le développeur ou l'équipe en proposant l'amélioration d'un bout de code.
Mais tout le monde n'a pas la connaissance du langage utilisé, cela se fait donc souvent sans code, et cela reste l'endroit où l'on suggère des améliorations.
Donc en pratique, les problèmes => Issues et les propositions => Pull Requests

Après, je suis d'accord que sur cette appli cela n'a pas grande importance.

**Comment by okpapt** [comment]
On y va comment sur Issues et les propositions => Pull Requests ?
Avez vous un lien ? J'ai beau cherché, je n'y arrive pas.
https://github.com/AdrienPoupa/AttestationDeplacement/pulls

En fait je n'ai que suivre le lien proposé sur la page principale :
https://github.com/AdrienPoupa/AttestationDeplacement

"Si tu es sûr d'avoir la dernière version et que le problème est toujours présent tu peux ouvrir un ticket"

**Comment by Nico207** [comment]
> Donc en pratique, les problèmes => Issues et les propositions => Pull Requests

@chcolin 
Je ne suis pas tout à fait d'accord... Les "[Pull Requests](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-requests)" doivent être réservées aux demandes d'intégration de code proposé par un autre développeur. C'est le but de cette section, et c'est même son nom "Demande de tirage du code" (oui ça sonne pas terrible en français 😁)
Après, chaque projet peut faire comme bon lui semble. Pour celui-ci, l'auteur indique un lien menant vers les issues, donc c'est bien ici qu'il fallait mettre les demandes d'évolution.

**Comment by chcolin** [comment]
@Nico207 Sur la définition, tu as raison, mais à l'usage tout le monde ne propose pas du code tout fait, loin de là, d'où mon désaccord avec ton assertion.
Après je reconnais que c'est une section un peu technique pour simplement dire "j'aimerais..."
Enfin oui, dans les FAQ il y a bien un lien pour remonter les problèmes sur _Issues_.
Bref, on se comprend :-)
