### ISSUE TITLE
Confirmation de suppression

### ISSUE THREAD

**Issue by Naomdatcha** [AdrienPoupa/AttestationDeplacement#21]
Ouvrir un dialogue de confirmation lors de l'appui sur l'icône suppression dans la liste des attestations générées. (En effet la proximité des icones pdf et partage créé un risque de fausse manip).

**Comment by okpapt** [comment]
en mode paysage (rotation de l'écran d'1/4 de tour) et c'est plus pratique (pour les icones placées à droite)
