### ISSUE TITLE
Optimisation du formulaire

### ISSUE THREAD

**Issue by Naomdatcha** [AdrienPoupa/AttestationDeplacement#22]
Le champ "demeurant" est ambigu par rapport à la manière dont celui-ci est généré dans le PDF : risque d'oubli de la ville et/ou du code postal. De plus une longue adresse créé des problèmes d'affichage du formulaire sur les petits écrans (le champ rajoute une ligne et déborde sur le champ suivant "fait à").

Il serait préférable de le faire comme dans le générateur officiel : trois champs "adresse", " ville" et "code postal". Le champ "fait à" n'aurait plus lieu d'être, le champ "ville" pouvant être pris en compte à la place.

Merci pour votre travail.

Adrien

**Comment by okpapt** [comment]
c'est ce que j'ai déjà demandé il y a peu.
au moins je ne suis pas le seul.

**Comment by AdrienPoupa** [comment]
Réglé en 1.3.0
