### ISSUE TITLE
short description trop longue

### ISSUE THREAD

**Issue by xinxinxinxinxin** [AdrienPoupa/AttestationDeplacement#23]
La description courte en français contenue dans le dossier fastlane est trop longue. Elle est normalement limitée à 80 caractères, du coup son affichage est coupé dans F-droid.

**Comment by AdrienPoupa** [comment]
https://github.com/AdrienPoupa/AttestationDeplacement/blob/master/fastlane/metadata/android/fr/short_description.txt modifié :)
