### ISSUE TITLE
Les données dans le QRCode ne sont pas au format Unicode

### ISSUE THREAD

**Issue by Nico207** [AdrienPoupa/AttestationDeplacement#25]
J'ai noté une différence entre le code officiel et le code généré par l'application.
Ce dernier n'encode pas les données au format Unicode.

Décodage du QRCode de l'application
<img src="https://user-images.githubusercontent.com/1179972/79234399-7d2dad00-7e6a-11ea-9339-4319ee70608e.png" data-canonical-src="https://user-images.githubusercontent.com/1179972/79234399-7d2dad00-7e6a-11ea-9339-4319ee70608e.png" width="300" />

Décodage du QRCode officiel
<img src="https://user-images.githubusercontent.com/1179972/79234407-8159ca80-7e6a-11ea-8554-e975d35584b6.png" data-canonical-src="https://user-images.githubusercontent.com/1179972/79234407-8159ca80-7e6a-11ea-8554-e975d35584b6.png" width="300" />

Suivant les lecteurs utilisés, cela peut entrainer une erreur d'affichage:
<img src="https://user-images.githubusercontent.com/1179972/79234419-86b71500-7e6a-11ea-96c5-7d9df36b0e6e.png" data-canonical-src="https://user-images.githubusercontent.com/1179972/79234419-86b71500-7e6a-11ea-96c5-7d9df36b0e6e.png" width="300" />

**Comment by chcolin** [comment]
Camera scanner ou mode auto (2D barre code imager) ?
Mon adresse est une "allée", et lorsque je scanne le document officiel et celui généré par l'appli d'Adrien, le "é" est mal interprété dans les deux cas.
On peut donc supposer donc que quelque soit l'appareil, non pas d'analyse de code, mais de lecture le résultat reste identique.

**Comment by Nico207** [comment]
L'interprétation du "e accent" (ou de tout autres caractères spéciaux) depend de l'application qui va lire le code. Si elle attend de l'Unicode et que de l'ASCII est lu (ou inversement), alors le caractère sera mal interprété.

Le QRCode officiel étant en Unicode, on peut **supposer** que l'application de lecture des forces de l'ordre peut afficher correctement de l'Unicode, mais rien n'indique qu'elle pourra afficher correctement de l'ASCII. (dans l'idéal, elle devrait pouvoir afficher les 2)

Reste plus qu'à se faire contrôler pour voir si c'est gênant 😁

**Comment by chcolin** [comment]
Oui tu as raison ce qui compte c'est ce que voit les forces de l'ordre, j'avoue que j'aimerais bien être contrôlé... :-)

Concernant l'interprétation, il suffit de voir que Créé, Prénom et à (dans date de naissance) s'affichent volontairement sans accent pour comprendre que dès qu'on va en mettre un il ne s'affichera pas correctement.
Ajouter un charset (ou le modifier) n'est donc pas forcément une bonne idée s'il n'y en a pas dans le code source. Et pour les plus inquiets, il suffit d'écrire sans accent :-)

Après, le CovidReader des policiers est un simple lecteur de QR code amélioré de retours chariots et de 2 variables conditionnelles.
En clair, il lit la même chose que nos smartphones, mais en plus, l'application :
- replace chaque élément sur une seule ligne pour une meilleure visibilité ;
- analyse si un élément est manquant et si la date et/ou l'heure sont erronés, surlignant alors en rouge l'élément suspect.

**Comment by okpapt** [comment]
@nico207, quelle appli utilises-tu ?

@chcolin
>     * analyse si un élément est manquant et si la date et/ou l'heure sont erronés, surlignant alors en rouge l'élément suspect.

Est-ce que les date/heure identiques de création et de sortie seraient susceptibles d'être surlignées en rouge ? Même  question s'il n'y a pas 5 mn que le qrcode a été généré ? 

Pour ma part, je félicite l'initiative, mais comme je trouve l'application trop éloignée de l'originale, je m'abstiens de l'utiliser. Voir mes propositions dans suggestion 2 (cliic sur  https://github.com/AdrienPoupa/AttestationDeplacement/issues/20 )

**Comment by chcolin** [comment]
@okpapt Non.
Sur le formulaire en ligne, la minute de l'heure de création correspond au clic sur le bouton "Générer l'attestation" tandis que la minute de l'heure de sortie est générée à l'affichage du formulaire vierge. Il suffit de mettre cette dernière à jour avant de cliquer pour que les deux soient identiques. Donc rien d'anormal.
Idem s'il y a moins de 5 mn que le pdf a été généré. L'application ne calcule pas la distance avec le domicile, par contre le fonctionnaire oui. Attention donc de ne pas se trouver à pied à 1 km de chez soit avec une attestation datant de 5 mn :-)

**Comment by Nico207** [comment]
@okpapt 
Sur smatphone, pour décoder un code-barre, il y a l'application [BinaryEye](https://github.com/markusfisch/BinaryEye), ou pour une simple lecture [Barcode Scanner](https://github.com/zxing/zxing)
Ou la même chose en ligne : [ZXing Decoder Online](https://zxing.org/w/decode.jspx)

Les 3 sont basées sur le même moteur de lecture (comme beaucoup d'autres) : ZXing


Pour les sorties, rien n'empêche dans un premier temps de prendre une version papier et d'utiliser cette application. En cas de contrôle, on peut donner la version papier et demander à l'agent si le QRCode est valide.

**Comment by okpapt** [comment]
@ Nico207 
J'ai déjà un lecteur de qrcode, mais binaryeye offre une possibilité que je n'avais pas. le binaire. Merci.

@chcolin 
Nous sommes bien d'accord.
Comme j'ajoute bien 20 mn entre le moment où je génère le doc sur le site gouv et celui où je sors (transférer le pdf sur le smartphone, éteindre l'ordi, m'habiller, descendre les poubelles, être dans la rue - je n'ai pas de forfait data), pour l'instant je n'utilise pas l'appli.

Si je savais comment on programme pour android, je m'y serai penché (je fais du php et du c++ arduino).

**Comment by chcolin** [comment]
@okpapt Justement, vous n'avez pas besoin de forfait, ni d'internet pour utiliser l'appli.
Vous faites ce que vous avez à faire, autant de temps qu'il le faut, et lorsque vous sortez de votre domicile, si vous avez déjà renseigné les champs de l'appli, vous n'avez plus qu'à cliquer et votre PDF sera disponible immédiatement.
Il n'y a pas plus simple, ni pratique et c'est tout l'intérêt de cette application.

**Comment by AdrienPoupa** [comment]
Réglé en 1.3.0
