### ISSUE TITLE
Définir la date et l'heure de sortie

### ISSUE THREAD

**Issue by baptiste0928** [AdrienPoupa/AttestationDeplacement#26]
Bonjour 👋 
Tout d'abord je voulais vous féliciter pour cette application, elle est très pratique ! Je souhaiterai proposer une suggestion d'amélioration.

Actuellement **la date et l'heure de sortie sont automatiquement remplies** lors de la génération de l'attestation. Il serait bien, selon moi, de proposer un champ pré-rempli que l'on peu au besoin modifier, comme sur le site du gouvernement.

J'en profite également pour signaler un léger problème d'affichage lorsque le contenu d'un champ est plus long que ce dernier (par exemple sur l'adresse) :

![](https://i.imgur.com/sBVDRcv.jpg)

J'espère que vous prendrez en compte ces remarques 😉

**Comment by Nico207** [comment]
Bonjour !

Dans la dernière version ([1.3.0](https://github.com/AdrienPoupa/AttestationDeplacement/releases/tag/1.3.0)), la date et l'heure sont maintenant saisissables 😉 

Effectivement, le problème d'affichage est reproductible sur tous les champs (même sur la dernière version)

**Comment by baptiste0928** [comment]
Parfait, merci pour votre réactivité ! 👍
