### ISSUE TITLE
Lecteur pdf introuvable sous Android 4.4.4

### ISSUE THREAD

**Issue by zorzibaffo** [AdrienPoupa/AttestationDeplacement#27]
Bonjour,

Version 1.3.0:

Je ne parviens pas à afficher le pdf avec un téléphone Xperia E3 + Android 4.4.4

Il n y a en revanche aucun problème avec un galaxy S4 mini + Lineageos 16.0 (=Android 9).

Le lecteur pdf est le même sur les deux téléphones: MuPDF mini.

**Comment by Nico207** [comment]
Bonjour !

Ce problème est probablement en rapport avec celui-ci : #14 
Il est corrigé dans la dernière version ([1.3.0](https://github.com/AdrienPoupa/AttestationDeplacement/releases)) et sera certainement disponible dans F-Droid dans quelques jours.

**Comment by zorzibaffo** [comment]
> Bonjour !
> 
> Ce problème est probablement en rapport avec celui-ci : #14
> Il est corrigé dans la dernière version ([1.3.0](https://github.com/AdrienPoupa/AttestationDeplacement/releases)) et sera certainement disponible dans F-Droid dans quelques jours.

Bonjour. J'ai bien installé la dernière version 1.3.0 sur les deux téléphones pourtant.

**Comment by okpapt** [comment]
J'ai testé sous android 4.4 et 6.0, le fichier pdf n'est pas généré ou affiché, l'appli reste bloquée (Ekstar Pdf Reader, Pdf Viewer Plus, librera reader pro).

**Comment by zorzibaffo** [comment]
Oui, testé aussi avec librera reader sous Android 4.4.4, et le problème demeurre.

**Comment by okpapt** [comment]
Peut-être faut-il définir l'association pdf -> application dans android ?
Mais je ne sait comment faire...

**Comment by zorzibaffo** [comment]
Oui, c'est possible. Mais je ne trouve pas comment faire pour le moment.

**Comment by baptiste0928** [comment]
Même problème sur un Wiko Lenny 3 sous Android 5.1 avec l'application en version 1.3.0. L'appareil dispose pourtant du lecteur PDF de base (celui de Google).

Aucun problème par contre avec LineageOS 16 (Android 9) et OnlyOffice en lecteur PDF.

**Comment by AdrienPoupa** [comment]
Salut,

Pour être clair, tu as le message t'indiquant que aucun lecteur PDF n'est détecté ?

**Comment by baptiste0928** [comment]
De mon côté (sur le Wiko Android 5.1), c'est ce message qui s'affiche.

**Comment by zorzibaffo** [comment]
> Salut,
> 
> Pour être clair, tu as le message t'indiquant que aucun lecteur PDF n'est détecté ?

Oui, j'ai ce même message on ne peut plus explicite.

**Comment by AdrienPoupa** [comment]
OK, on dirait que en dessous de Android N (7) ca pose problème. C'est peut-être lié au FileProvider et il faudrait peut-être faire deux intents différents selon la version.

https://github.com/AdrienPoupa/AttestationDeplacement/blob/master/app/src/main/java/com/poupa/attestationdeplacement/AttestationAdapter.java#L162

@Nico207 si tu veux essayer de creuser ça ça m'aiderait :p

**Comment by Nico207** [comment]
@AdrienPoupa 
C'est pas tout simple cette affaire...🤔
Je n'ai pas d'appareil avec un Android<7, du coup je suis passé par un émulateur sous Android 5.1
C'est là que ça devient rigolo...
Test avec :
- [muPDF](https://f-droid.org/en/packages/com.artifex.mupdf.viewer.app/) 1.15.1 : il est bien détecté, mais il plante au démarrage.
- muPDF 1.16.1 : il n'est pas détecté
- ([Pdf Viewer Plus](https://f-droid.org/en/packages/com.gsnathan.pdfviewer/)) 3.3 : pas détecté
- ([CuprumPDF](https://f-droid.org/en/packages/org.ninthfloor.copperpdf/)) 1.2.1 : détecté, s'ouvre, mais n'affiche rien

Ils sont semblent pourtant déclarés correctement (android:mimeType="application/pdf")


--Edit 1
Quand je demande d'afficher toutes les applications pouvant ouvrir un fichier (mimeType = "\*/\*"), les applications ne sont pas affichées. 
Par contre, si j'ouvre un pdf à partir du navigateur (URL), il me propose PDV Viewer Plus (qui accepte d'ouvrir les URL)

--Edit 2
Après quelques modifications dans le manifest de PDFViewer, j'ai pu le faire détecter comme il faut.
Si j'ai un peu de temps, j'irais ouvrir un ticket sur leur dépôt.


Le problème semble donc plus venir des lecteurs que de la façon dont la demande d'ouverture est faite.

**Comment by AdrienPoupa** [comment]
Ok, merci beaucoup pour tes recherches ! Mais dans ce cas, ce qui m'étonne c'est que le comportement change avec la version d'Android alors que les applis sont les mêmes :/

**Comment by baptiste0928** [comment]
Je ne m'y connait pas assez en application Android pour vous aider, mais à mon avis, **il faudrait intégrer directement le lecteur PDF dans l'application** pour éviter les problèmes de compatibilité entre les versions. J'ai cherché quelques minutes et ait trouvé [pdfview](https://github.com/Dmitry-Borodin/pdfview-android) qui pourrait convenir, mais ce n'est pas compatible avec Android 4.4 😕

**Comment by okpapt** [comment]
Qui a un lecteur de pdf qui fonctionne avec cette application sous android < 7 ?

Serait-il possible de définir dans quel dossier le pdf pourrait être enregistrer afin de l'ouvrir avec le lecteur pdf de son choix ?

**Comment by AdrienPoupa** [comment]
J'ai trouvé le problème ! Les lecteurs externes n'avaient pas la permission de lire le PDF, qui était contenu dans la mémoire interne de l'application.

Sur Android >= N on avait le FileProvider qui s'en chargeait mais il fallait aussi l'appeler sur les versions plus anciennes, ainsi que manuellement faire un `grantUriPermission` sur les applis du chooser: https://stackoverflow.com/questions/18249007/how-to-use-support-fileprovider-for-sharing-content-to-other-apps/32950381#32950381

J'ai testé muPDF sur Android 4.4 et ça fonctionne

**Comment by okpapt** [comment]
Heu ?!?!?
Concrètement, ça veut dire quoi pour les utilisateurs lambda comme moi ?
Parce que le lien sur strackoverflow; même une fois traduit, pour moi ça reste un peu du charabia.
La seule chose que je pense avoir compris, c'est que ce serait du code à ajouter dans l'appli, mais laquelle ? Le lecteur pdf ou l'attestation de sortie ?

Test ce matin avec avec la version 1.4.0 sous android 4.4.4  :
https://f-droid.org/en/packages/com.artifex.mupdf.viewer.app/
    muPDF 1.15.0 (50) : il est bien détecté, mais il plante au démarrage.
    muPDF 1.15.1 (60) : il est bien détecté, mais il plante au démarrage.
    muPDF 1.16.1 (70) : il n'est pas détecté
https://mupdf.com/downloads/index.html
    mupdf-android-viewer-1.15.0-universal.apk : il est bien détecté, mais il plante au démarrage.

Serait-il possible de générer dans la mémoire de l'appli, l'ensemble du document "pdf" avec le qrcode ? De ce fait, plus besoin de lecteur pdf puisque c'est directement affiché à l'écran.

**Comment by Nico207** [comment]
@okpapt 
Je pense que le message était plus destiné aux développeurs qui auraient le même problème et qui voudraient une solution.

Je viens de tester avec un émulateur sous Android 5.1 et la dernière version de l'application AttestationDeplacement ([V1.4.0](https://github.com/AdrienPoupa/AttestationDeplacement/releases/tag/1.4.0)) : ça fonctionne avec tous les lecteurs PDF cités plus haut.
Avez-vous testé la dernière version ?

@AdrienPoupa 
J'avais bien suivi la piste de l'emplacement du fichier, mais j'avais juste testé en mettant le fichier dans un répertoire plus commun (Download, Document...), mais sans résultats.
Merci pour le lien, je garde ça sous le coude, je suis persuadé que ça va me resservir. 👍

**Comment by okpapt** [comment]
@Nico207 : oui, j'ai édité mon message pour apporté ces précisions.
