### ISSUE TITLE
pour plus de simplicité et de rapidité

### ISSUE THREAD

**Issue by okpapt** [AdrienPoupa/AttestationDeplacement#28]
Bonjour,
Merci pour les améliorations apportées.

Cependant, pour un plus grand confort d'utilisation et une présentation plus lisible, je suggère une réorganisation en classant de haut en bas du plus employé au moins  utilisé/modifié.

La date/heure de sortie tout en haut (merci pour le remplissage automatique).

Le bouton de génération du qrcode juste après l'heure de sortie.

Le motif de sortie change moins souvent, mais c'est un peu long de tout lire pour faire le bon choix. Aussi je propose de ne cocher que le mot figurant sur l'attestation (travail, courses, sante, famille, sport, judiciaire,  avec à côté un ? ; en cliquant dessus il afficherait un pop-up contenant le texte complet.

Entre le motif de sortie et les coordonnées, un champs avec une valeur en minutes pour anti-dater automatiquement la date/heure de création à partir de celle saisie pour la sortie.

Les coordonnées, on ne les saisit qu'une fois, donc elles devraient être toutes en bas.

Afficher plus grand et sur fond opaque le qrcode, tout en mettant l'application en arrière plan, je doute fort que les forces de l'ordre apprécient de voir que c'est un qrcode généré en dehors du site officiel.

En espérant que ces propositions ergonomiques seront lues, comprises et retenues pour une intégration prochaine.
Bonne continuation.
Dominique.

**Comment by AdrienPoupa** [comment]
Bonjour, merci pour les suggestions mais je préfère garder les champs aussi proche que possible du formulaire officiel.
