### ISSUE TITLE
Encore d'actualité ? 

### ISSUE THREAD

**Issue by pmiossec** [AdrienPoupa/AttestationDeplacement#3]
Je ne sais pas si l'application se veut encore d'actualité (je viens d'en apprendre l'existence).

Si ce n'est pas le cas, ça serait bien  de la retirer du store (si c'est possible) ou d'inquer qu'elle est obsolète.

Sinon, il faudrait:
* mettre à jour l'attestation dans la nouvelle version.
* corriger le calendrier qui retourne le mauvais mois (ajouter 1 car il renvoie juin à la place de juillet par exemple) et mettre une valeur par défaut à celle précédemment renseignée si elle existe ou à une date dans le passé (1/1/2000 par exemple) pour moins avoir à scroller. Et empêcher les dates de naissance dans le futur. 
* éventuellement fixer le bug qui empêche d'enregistrer la signature lors de la 1ère utilisation (lorsqu'on relance, ça marche). 

Merci

**Comment by AdrienPoupa** [comment]
Salut,

Je suis en train de travailler pour mettre à jour le PDF et aussi générer le barcode qui sera dans l'application officielle.

Je te dirai quand c'est fait.

**Comment by pmiossec** [comment]
OK. Merci beaucoup pour la réponse et bon courage !

**Comment by AdrienPoupa** [comment]
J'ai mis à jour l'application: elle a désormais le PDF le plus récent et génère aussi un QR code conforme a celui de l'application officielle.

J'ai mis a jour les screenshots: https://github.com/AdrienPoupa/AttestationCoronavirus/tree/master/fastlane/metadata/android/fr/images/phoneScreenshots

Il n'y a plus qu'à attendre le build de F-Droid.

**Comment by AdrienPoupa** [comment]
J'ai rajouté l'APK ici si tu veux tester: https://github.com/AdrienPoupa/AttestationCoronavirus/releases/download/0.0.4/app-release.apk

**Comment by pmiossec** [comment]
Je n'arrive pas à l'installer.
J'ai un avertissement de play protect, je choisi 'Install anyway' mais j'ai le message 'App not installed'.

**Comment by pmiossec** [comment]
J'ai eu la mise à jour F-droid.
C'est beaucoup mieux ;)

Y'a juste un petit problème qui ne (me) permet pas de l'utiliser (l'après-midi ;) ).
L'heure de génération n'est pas affichée au bon format, sur 24h, et donc pour `15h`, ça met `03`

**Comment by AdrienPoupa** [comment]
Ok je regarde ça ce soir (pour moi!)
