### ISSUE TITLE
La case n'est pas cochée dans le pdf généré. 

### ISSUE THREAD

**Issue by pmiossec** [AdrienPoupa/AttestationDeplacement#30]
(dans la version 1.3)

C'est tout 😉

**Comment by AdrienPoupa** [comment]
Il semble y avoir un bug sur la case motif familial effectivement

**Comment by AdrienPoupa** [comment]
Je viens de tester tous les cas de figures et ca fonctionne. Quelle case posait problème?

**Comment by pmiossec** [comment]
So sorry. I just discovered that it's the main pdf viewer  (EzPdf Viewer) that I use that doesn't display the checks 😕
