### ISSUE TITLE
Application indisponible sur Google Play

### ISSUE THREAD

**Issue by baptiste0928** [AdrienPoupa/AttestationDeplacement#34]
Bonjour tout le monde !

Je viens de remarquer que **l'application n'est plus disponible [sur Google Play](https://play.google.com/store/apps/details?id=com.poupa.attestationdeplacement)**. Sûrement qu'à cause de ces applications qui volent les données, Google a fait le ménage sans regarder en détails 😕 

Bon, je ne suis pas sûr qu'on y puisse grand chose, mais l'application est encore [sur F-Droid](https://f-droid.org/fr/packages/com.adrienpoupa.attestationcoronavirus/). Cette issue est juste pour vous prévenir au cas où vous n'étiez pas au courant (ce qui m’étonnerait), mais aussi pour proposer quelques idées à propos de ça.

Il faudrait - à mon avis - **plus développer le readme pour présenter l'application** (avec liens de téléchargement et cie), voire faire un site web avec GitHub Pages. Si la suggestion vous branche, je pourrais faire une petite page de présentation 😀

**Comment by AdrienPoupa** [comment]
J'ai envoyé une contestation en disant qu'il n'y avait pas de publicité et que le code était disponible mais je n'y crois pas trop.

Je vais envoyer l'application sur d'autres stores.

**Comment by okpapt** [comment]
Je ne suis pas certain que ce soit une bonne chose de mettre l'application sur le google store, il ne faudrait pas que les forces de l'ordre la connaissent et nous verbalisent pour son utilisation.
Les autres stores étant moins fréquentés, offrent une diffusion plus facile "sous le manteau".
Pour ma part, je préfère venir ici pour être certain d'avoir la dernière version.

**Comment by AdrienPoupa** [comment]
> Je ne suis pas certain que ce soit une bonne chose de mettre l'application sur le google store, il ne faudrait pas que les forces de l'ordre la connaissent et nous verbalisent pour son utilisation.

Au nom de quoi? Y a-t-il une loi empêchant son utilisation?

**Comment by okpapt** [comment]
Effectivement, autant pour moi, je n'ai pas trouvé d'information stipulant qu'il était obligatoire d'utiliser spécifiquement un site, un document officiel, puisqu'on peut le rédiger manuellement et sobrement. (Pour occuper les gosses, je vais leur faire dessiner le qrcode.)

https://www.gouvernement.fr/info-coronavirus
Règlementation du confinement (extraits)

**Je n'ai pas d’imprimante chez moi, comment faire ?**
    l’attestation de déplacement dérogatoire peut être imprimée ou rédigée sur papier libre selon le modèle téléchargeable en ligne ;
    l’attestation employeur doit être signée par l’employeur.

**Dois-je recopier l’entièreté de l’attestation ou puis-je simplement inscrire le motif de ma sortie sur papier libre ?**
Il est nécessaire de recopier :
_ la partie correspondant à son identité ;
_ la mention « certifie que mon déplacement est lié au motif suivant autorisé par l’article 3 du décret du 23 mars 2020 prescrivant les mesures générales nécessaires pour faire face à l’épidémie de Covid-19 dans le cadre de l’état d’urgence sanitaire » ;
_ la ligne correspondant au motif ;
_ le lieu, la date, l’heure.
**Et de signer, dans tous les cas.**

PS: le document papier ne précise pas _adresse, code postal et ville,_ mais simplement _demeurant_.

**Comment by AdrienPoupa** [comment]
C'est de retour!

https://play.google.com/store/apps/details?id=com.poupa.attestationdeplacement
