### ISSUE TITLE
MERCI

### ISSUE THREAD

**Issue by okpapt** [AdrienPoupa/AttestationDeplacement#35]
Merci pour cette nouvelle mouture.
Merci pour la simplification du choix du motif de déplacement et le popup.
Merci pour l'ordre adresse - code - postal dans le qrcode, je ne peux tester le pdf.
Merci pour le fond sombre derrière le qrcode.
Merci pour le qrcode bien plus grand.

Je continue de penser qu'en positionnant ainsi de haut en bas :
- la date et l'heure de sortie
- le bouton générer
- le motif de sortie
- les coordonnées
nous fera gagner du temps et nous éviterait quelques mouvements du pouce, susceptibles de générer à la longue une tendinite (il faut aussi penser aux vieux plein d'arthrose). 

Serait-il possible de mémoriser le motif de la sortie (comme pour les coordonnées) et de ne permettre qu'un seul choix ?
Certes sur le site officiel il est possible de faire aucun ou plusieurs choix, mais un policier m'a certifier qu'il ne devait y avoir qu'un seul motif de sortie par attestation, "ce n'est pas cumulable" m'a t il dit.

Encore Merci.

**Comment by AdrienPoupa** [comment]
> Certes sur le site officiel il est possible de faire aucun ou plusieurs choix, mais un policier m'a certifier qu'il ne devait y avoir qu'un seul motif de sortie par attestation, "ce n'est pas cumulable" m'a t il dit.

J'aurais plutôt confiance envers le générateur officiel qui autorise plusieurs motifs ainsi que des sources officielles: http://www.vaucluse.gouv.fr/covid-19-faq-attestations-de-deplacement-ce-qu-il-a13020.html

"Il est conseillé de grouper vos sorties. Il est donc possible d’indiquer plusieurs motifs."

**Comment by okpapt** [comment]
Sur cette même FAQ il est indiquée :
**_L’attestation peut-elle être remplie sur mobile/ordinateur et présentée directement depuis son smartphone ?
Non. À ce stade, seules sont reconnues valables les attestations officielles imprimées et les attestations sur l’honneur rédigées sur papier libre._**

Quand on clique dans l'encadré pour obtenir le document 

**_Ces documents sont téléchargeables sur le site internet de la préfecture :
http://www.vaucluse.gouv.fr/covid-19-attestation-derogatoire-de-deplacement-a13005.html_**

on est redirigé vers une page qui n'a plus le document.


Il est vrai que sa dernière mise à jour date du :
........
........
........
........
20/03/2020

---------------------------------------------------------------------------------------------------

Cependant, en totale contradiction avec le policier et confirmant votre réponse, sur 
https://www.gouvernement.fr/info-coronavirus
il y est indiqué dans **Règlement du confinement**

Peut-on cocher plusieurs cases et grouper ses sorties ?
Vous êtes incités à limiter vos sorties aux cas limitatifs énumérés, il est donc conseillé de grouper vos sorties et il est donc possible d’indiquer plusieurs motifs.

L’attestation de déplacement dérogatoire peut-elle se faire en numérique, plutôt que sur papier ?
Oui. Vous pouvez créer votre attestation de déplacement dérogatoire en ligne sur le site du ministère de l’Intérieur : https://www.interieur.gouv.fr/Actualites/L-actu-du-Ministere/Attestation-de-deplacement-et-de-voyage

Est-ce que les attestations papier restent valables ?
Oui.

Comment le dispositif numérique fonctionne-t-il ?
Il suffit de remplir un formulaire en ligne, disponible sur le site internet du ministère de l’Intérieur.
renseignez les informations relatives à votre identité et adresse, et indiquez le motif de sa sortie,
 un fichier PDF est alors généré. Ce document comporte un QR Code comprenant l’ensemble des données du formulaire, ainsi que la date et l’heure de génération du document.
Ce fichier doit être présenté sous forme numérique lors d’un contrôle, grâce à votre smartphone ou votre tablette numérique.

Pourquoi ne pas avoir conçu une application pour smartphone ?
Le formulaire en ligne est plus simple à utiliser pour le plus grand nombre et permet de faciliter les éventuelles mises à jour au cas où l’attestation viendrait à évoluer

---------------------------------------------------------------------------------------------------

Reste un dilemme concernant la signature, Pour la version papier du début, toujours disponible à télécharger, imprimer et remplir à la main, il y a toujours  l'endroit indiqué pour signer. Alors que sur la version numérique, il n'y a plus cette notation. Il est vrai qu'il est difficile de signer physiquement un document "virtuel".

**Comment by okpapt** [comment]
Quelle solution pour  **Lecteur pdf introuvable sous Android 4.4.4** #27
