### ISSUE TITLE
aucun pdf sous android 4.4.4 et 6

### ISSUE THREAD

**Issue by okpapt** [AdrienPoupa/AttestationDeplacement#36]
Bonjour,
Le sujet a déjà été abordé, mais il ne me semble pas qu'une solution ait été apportée.
Dernièrement j'ai testé avec la version 1.4.0 sous android 4.4.4 :
https://f-droid.org/en/packages/com.artifex.mupdf.viewer.app/
muPDF 1.15.0 (50) : il est bien détecté, mais il plante au démarrage.
muPDF 1.15.1 (60) : il est bien détecté, mais il plante au démarrage.
muPDF 1.16.1 (70) : il n'est pas détecté
https://mupdf.com/downloads/index.html
mupdf-android-viewer-1.15.0-universal.apk : il est bien détecté, mais il plante au démarrage.

Serait-il possible de générer dans la mémoire de l'appli, l'ensemble du document "pdf" avec le qrcode ? De ce fait, plus besoin de lecteur pdf puisque c'est directement affiché à l'écran.

Merci.

**Comment by baptiste0928** [comment]
Bonjour @AdrienPoupa, je vois que le problème est *à priori* résolu avec le commit 290b86f7f58353160b20135cbdb0bbe7dfe3ef2f, mais ce n'est pas encore disponible en release.
Serait il possible de mettre à disposition **un apk intégrant ces modification** ? 😅

**Comment by AdrienPoupa** [comment]
https://github.com/AdrienPoupa/AttestationDeplacement/releases/tag/1.4.1 :)

**Comment by baptiste0928** [comment]
Parfait, merci beaucoup ! 😀
