### ISSUE TITLE
Erreur d'installation de l'apk 1.4.0 sur Android 10 - Samsung Galaxy 10

### ISSUE THREAD

**Issue by Valeryan24** [AdrienPoupa/AttestationDeplacement#37]
Bonjour,

Merci pour votre travail. La version FDroid n'étant plus à jour (1.1.0) - d'autres programmes ont eu des updates ces derniers jours mais hélas pas AttestationDeplacement - j'ai essayé de télécharger l'apk directement sur Github et de l'installer, notamment afin d'avoir la "Correction QRCode pour le rendre identique à l'original".

En essayant, j'ai juste un pop-up "Erreur" et l'installation échoue. Je peux éventuellement faire d'autres manips pour avoir des logs. En théorie les sources externes sont bien autorisées, puisque j'ai pu mettre FDroid...

**Comment by AdrienPoupa** [comment]
Essaie de désinstaller la version installée, puis retente d'installer l'APK

**Comment by Valeryan24** [comment]
Merci, mais même avant d'installer la verion FDroid, c'était impossible.

Sauf que autant pour moi, c'est de ma faute, j'avais sous-estimé le niveau de protection d'Android 10 : il gère l'autorisation des applications inconnues par programme, et non plus globalement, et je n'avais pas autorisé "Fichiers" pour cela (comme c'est l'appli par défaut du système, je pensais que c'était OK)...

Donc c'est bon, elle s'installe bien (à côté de celle de FDroid que j'ai supprimé), tout est nickel, merci !
