### ISSUE TITLE
100km

### ISSUE THREAD

**Issue by okpapt** [AdrienPoupa/AttestationDeplacement#38]
Bonjour,
Je propose de créer une appli qui à partir de l'enregistrement du domicile (lon et lat du gps intégré), afficherait automatiquement la distance d'où l'on se trouve. Jusqu'à 80km, le texte est vert sur fond noir, entre 90km et 100km le texte est orange sur fond noir, entre 100km et 105, le texte est rouge sur fond noir, au delà le texte est noir sur fond rouge. 
La version 2.0 ajouterait un triangle indiquant la direction du lieu de départ, circulant sur un cercle autour de l'indication de distance.

Une autre appli plus graphique, afficherait notre position sur une carte hors ligne, qui serait créée automatiquement en ligne par l'application, avec un fichier de configuration identique ou compatible à mobac ou oruxmaps pour les sources des cartes. Cette carte serait un cercle d'un rayon de 120km autour de l'enregistrement du domicile (lon et lat du gps intégré), La première appli pourrait y être intégrée dans un coin de la carte. 
Personnellement, j'ai déjà créé une telle carte pour oruxmaps avec mobac, mais ce n'est pas si simple. Il est aussi possible de crée la carte directement depuis oruxmap, mais c'est une véritable usine à gaz, d'où cette proposition simplifiée pour "tout le monde" ou "le monde entier". Si ma mémoire est bonne, les sources de mobac et oruxmap seraient disponibles.
https://mobac.sourceforge.io/    et aussi   https://sourceforge.net/p/mobac/code/
https://github.com/topics/oruxmaps     et aussi    https://www.oruxmaps.com/cs/en/

**Comment by AdrienPoupa** [comment]
Bonjour,

Il y a déjà des sites permettant de le faire, je ne souhaite pas rajouter cette fonctionnalité à l'application:

https://www.letelegramme.fr/static/ftp/dossier/data/dataviz/confinement/index-100.php

https://www.esrifrance.fr/deconfinement-100-km/

**Comment by okpapt** [comment]
Ce n'était pas à ajouter à l'attestation (qui ne sera plus utile après le 11 mai), mais une nouvelle application à créer, pour l'avoir autonome sur le tel sans connexion data.
