### ISSUE TITLE
merci pour le pdf

### ISSUE THREAD

**Issue by okpapt** [AdrienPoupa/AttestationDeplacement#39]
Il fonctionne maintenant sur la majorité des applications que j'ai testées.
Par contre j'ai un doute sur la police utilisée pour la croix dans le choix du motif.
Merci encore pour cette release.

**Comment by AdrienPoupa** [comment]
J'en suis ravi !

A ma connaissance la librairie que j'utilise (iTextPDFg) ne permet pas de changer comment cocher une case.
