### ISSUE TITLE
Impossible de mettre la date de naissance

### ISSUE THREAD

**Issue by crazybusta94** [AdrienPoupa/AttestationDeplacement#4]
Bonjour, j'ai un problème sur mon téléphone, il est impossible de mettre la date de naissance, dès que je clique à l'endroit ou mettre la date de naissance, ça revient à la page principale.

Tester sur la version 0.0.4 et 1.0.0
Je suis sur android 6 mon téléphone est un xiaomi redmi note 3 pro

ça fonctionne correctement sur bluetacks, sauf l'heure qui n'est pas au format 24h.
Mais sur mon téléphone impossible de mettre la date de naissance

**Comment by AdrienPoupa** [comment]
Salut,

ça fonctionne bien chez moi (Android 9) donc ça doit venir de Android 6. Je vais regarder et te dire ça.

**Comment by AdrienPoupa** [comment]
C'est réglé en 1.0.1: https://github.com/AdrienPoupa/AttestationCoronavirus/releases/tag/1.0.1
