### ISSUE TITLE
Application indisponible sur F-Droid

### ISSUE THREAD

**Issue by stuart12** [AdrienPoupa/AttestationDeplacement#40]
bonjour, l’application n'est plus disponible sur F-Droid. Le [lien vers F-Droid](https://f-droid.org/packages/com.poupa.attestationdeplacement) dans le [Readme](https://github.com/AdrienPoupa/AttestationDeplacement/blob/master/README.md) donne un 404.

Au secours, je suis coincé avec la version 1.1.0.

**Comment by AdrienPoupa** [comment]
Oui, l'ancien nom de package a été archivé et le nouveau arrivera bientôt: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/6616

En attendant, tu peux la télécharger sur GitHub ou le Play Store.

**Comment by AdrienPoupa** [comment]
Elle est revenue sous son nouveau nom !

https://f-droid.org/packages/com.poupa.attestationdeplacement/
