### ISSUE TITLE
Bientôt une nouvelle version de l'application ?

### ISSUE THREAD

**Issue by okpapt** [AdrienPoupa/AttestationDeplacement#41]
Pour faire respecter les nouvelles règles qui vont intervenir à partir du 11 mai et notamment l'interdiction de se déplacer au-delà des 100 km de son domicile, le gouvernement a décidé d'une nouvelle attestation.

Bientôt une nouvelle version de l'application ?

**Comment by AdrienPoupa** [comment]
Effectivement ça semble nécessaire quand le nouveau fichier PDF sera disponible

**Comment by AdrienPoupa** [comment]
1.6.0: Ajout de l'auto-attestation pour les transports en Ile-de-France

La nouvelle attestation pour les déplacements > 100km n'est pas encore disponible

**Comment by okpapt** [comment]
Version papier à télécharger :
https://www.interieur.gouv.fr/Actualites/L-actu-du-Ministere/Deconfinement-Declaration-de-deplacement
Version en ligne :
https://media.interieur.gouv.fr/deplacement-covid-19/
Bon courage et Merci.

**Comment by AdrienPoupa** [comment]
Réglé en 1.7.0: https://github.com/AdrienPoupa/AttestationDeplacement/releases/tag/1.7.0
