### ISSUE TITLE
couvre-feu covid 19

### ISSUE THREAD

**Issue by okpapt** [AdrienPoupa/AttestationDeplacement#42]
Bonjour,

Merci encore pour le travail réalisé et la rapidité de votre réactivité lors du confinement et aux différentes étapes durant la sortie du confinement.

Auriez-vous une nouvelle version pour ceux qui doivent se déplacer durant le couvre-feu en France ?
https://www.gouvernement.fr/info-coronavirus/ressources-a-partager

- attestation dérogatoire pour les particuliers :
https://www.gouvernement.fr/sites/default/files/16-10-2020-attestation-de-deplacement-derogatoire1.pdf

- justificatif déplacement professionnel :
https://www.gouvernement.fr/sites/default/files/16-10-2020-justificatif-de-deplacement-professionnel.pdf

J'ai déjà l'atestation papier d'un de mes employeurs, avec entête, date et signature, que je dois compléter.
Comme c'est la même mise en page à partir du document gouvernemental, est-il possible de générer une application avec des champs "image" pour y inclure l'entête et la signature pour chacun d'eux ?

Cordialement.

**Comment by AdrienPoupa** [comment]
C'est fait, je mettrai a jour pour l'attestation de déplacement v2
