### ISSUE TITLE
Nouvelle version 29/10/2020

### ISSUE THREAD

**Issue by jisse44** [AdrienPoupa/AttestationDeplacement#46]
Bonjour,

Nouvelles versions de l'attestation ici: https://www.interieur.gouv.fr/Actualites/L-actu-du-Ministere/Attestations-de-deplacement
avec de nouveaux motifs.

**Comment by okpapt** [comment]
S'il y a de nouveaux motifs, pour commencer je veux bien une version Halloween !
Nan, je rigole ...

**Comment by AdrienPoupa** [comment]
Parfait merci!
