### ISSUE TITLE
adresse tronquée

### ISSUE THREAD

**Issue by Mxnxxl** [AdrienPoupa/AttestationDeplacement#47]
Bonjour, avec la dernière version, lorsque l'adresse ( rue + CP + Ville) comporte trop de caractères, elle est tronquée sur le pdf généré. Dans mon cas il manque quelques lettres au nom de la ville.

**Comment by okpapt** [comment]
Bonsoir Mxnxxl, De quelle dernière version est-il question ? La 2.0.0 pour le couvre-feu n'a plus de raison d'être, puisqu'il y a un nouveau document pour le confinement actuellement en cours.

**Comment by tarbib** [comment]
Bonsoir, j'ai toujours ce problème sur la version 2.0.0.

**Comment by dolmen** [comment]
@tarbib La version 2.0.0 est obsolète. La dernière est la 3.1.0.

Pour se tenir à jour, c'est ici : https://github.com/AdrienPoupa/AttestationDeplacement/releases
