### ISSUE TITLE
Aucune case cochée sur le PDF

### ISSUE THREAD

**Issue by vince2bir** [AdrienPoupa/AttestationDeplacement#49]
L'attestation en PDF ne comprend aucune case cochée quelque soit les choix faits.
[ajout : ne fonctionne pas sur certains lecteurs ezPDF Reader ou aldiko par exemple
fonctionne sur le lecteur PDF de dropbox et googledrive]

**Comment by Valeryan24** [comment]
Sur le lecteur Pdf d'Office Android et le libre Document Viewer, la case apparaît bien cochée également.

**Comment by okpapt** [comment]
sur une précédente version, il y a eu des échanges et des tests d'applications pdf sur android pour bien lire les pdf.

**Comment by AdrienPoupa** [comment]
J'ai changé la façon de générer le PDF, tout devrait rentrer dans l'ordre dans la 3.1.0.
