### ISSUE TITLE
Plusieurs types d'attestations

### ISSUE THREAD

**Issue by Pierstoval** [AdrienPoupa/AttestationDeplacement#50]
Le gouvernement a mis en ligne plusieurs types d'attestations : https://www.interieur.gouv.fr/Actualites/L-actu-du-Ministere/Attestations-de-deplacement

Il serait utile de pouvoir toutes les générer depuis l'appli.

Je n'ai jamais fait de Java, et ne connais pas vraiment les méthodes de build. Une idée d'où commencer pour tenter de contribuer ? 😉

**Comment by okpapt** [comment]
plusieurs applications, de façon à garder la rapidité et l'ergonomie, et cas d'oubli en partant de chez soi et qu'un contrôle est en vue...

il est indiqué sur https://media.interieur.gouv.fr/deplacement-covid-19/ que leur code source se trouve sur https://github.com/LAB-MI/attestation-deplacement-derogatoire-q4-2020 j'ai regardé leur explication et je n'ai rien compris.

**Comment by dolmen** [comment]
Les autres types d'attestation (par exemple l'attestation employeur) ont une plus longue durée de validité. Et elle doit être remplie par l'employeur.

Bref aucun intérêt d'ajouter les autres types d'attestations.
