### ISSUE TITLE
Coquilles dans la description pop-up des motifs de déplacement

### ISSUE THREAD

**Issue by Valeryan24** [AdrienPoupa/AttestationDeplacement#51]
Bonjour,

Merci beaucoup pour votre travail, mise à jour d'appli qui permet de générér des pdf conformes d'attestation en moins de 10 secondes, et le repush sur F-Droid.

Juste une petite remarque, pas très grave car le texte sur le Pdf final est correct, mais dans la fenêtre explicitant les divers motifs de déplacement, il y a quelques coquilles : 

Travail : "Déplacements établissement entre enseignement le domicile et oulede lieu formation... ne un pouvant être différés"

Achats : "... des achats de première des achats nécessité"

Rien qui empêche de l'utiliser !

**Comment by AdrienPoupa** [comment]
Bien vu, merci!
