### ISSUE TITLE
Duplication du motif 

### ISSUE THREAD

**Issue by isidor007** [AdrienPoupa/AttestationDeplacement#52]
Bravo pour votre application.

Bug mineur qui n'empêche en rien l'utilisation.

Après la génération d'une attestation, si l'utilisateur fait un retour au formulaire, puis un nouvelle génération sans toucher au motif, les motifs sont dupliqués 
après régénération.

![Screenshot_20201030-211050](https://user-images.githubusercontent.com/73718689/97753087-7e1be880-1af5-11eb-8a2b-548f50bfa29c.png)

A votre disposition si besoin

**Comment by okpapt** [comment]
Moi j'aime bien cette "duplication", tant que l'heure est mise à jour, ça évite d'avoir à tout resaisir...

**Comment by MagTun** [comment]
Lorsque je fais ça, la deuxième application générée n'a aucune case cochée.
