### ISSUE TITLE
CheckBox "sport et animaux ..."

### ISSUE THREAD

**Issue by isidor007** [AdrienPoupa/AttestationDeplacement#54]
Bug ergo mineur
La CheckBox "sport et animaux .." n'est pas bien positionnée. Probablement dû au fait qu elle soit sur 2 lignes.
Téléphone: Pixel 4a

**Comment by AdrienPoupa** [comment]
Aucun problème chez moi, possible d'avoir un screenshot?

**Comment by GreenBlood** [comment]
(Sur un OnePlus 6)
Je sais pas si c'est le même comportement, mais ici la checkbox est un peu décalée.

EDIT : En revanche en mode paysage les cases sont bien alignées.

![Screenshot_20201104-192333](https://user-images.githubusercontent.com/6583431/98153391-6668a980-1ed3-11eb-91aa-048de58af67b.jpg)

**Comment by Otiel** [comment]
Idem sur S10e.

![Screenshot_20201104-204714_Attestation de dplacement](https://user-images.githubusercontent.com/3851902/98164217-4097d080-1ee4-11eb-824f-0fed6699fa7d.jpg)

**Comment by okpapt** [comment]
Est-ce vraiment gênant que ce ne soit pas bien positionné, pour une appli qui disparaitra avec le covid ?
Je remercie Adrien Poupa qui nous propose **gratuitement** une application fonctionnelle et je pense qu'il a suffisamment à faire ailleurs que de s'occuper de ces détails, qui n’apparaissent pas sur le pdf.

**Comment by marie-bnl** [comment]
Les issues ne sont pas faites pour critiquer négativement sans raison, mais bien pour améliorer l'application. Si le développeur désire la prendre en compte et y trouver une solution, ou n'importe quel autre membre de la communauté d'ailleurs, il peut le faire, mais s'il juge l'issue impertinente, il peut aussi fermer l'issue, ainsi, chaque issue est la bienvenue, et le but de @isidor007 n'était absolument pas de se plaindre.
