### ISSUE TITLE
Reminder lorsque l'on quitte le domicile

### ISSUE THREAD

**Issue by adrian3d** [AdrienPoupa/AttestationDeplacement#55]
Bonjour et merci pour cette application.

Une idée de feature pour les étourdis comme moi : pouvoir rappeler à l'utilisateur qu'il doit générer une attestation quand il quitte le domicile. Cela implique la géo-localisation activée.

Cela peut paraître hors-scope, j'en ai conscience.

Bon courage dans tous les cas.

**Comment by okpapt** [comment]
pose un post'it sur la porte !

**Comment by AdrienPoupa** [comment]
Merci pour la suggestion mais je préfère garder l'application aussi simple que possible, aussi je ne souhaite pas ajouter de géo-localisation
