### ISSUE TITLE
feature request: une option pour garder la dernière case cochée (ou pour choisir une case cochée par défaut)

### ISSUE THREAD

**Issue by WiliTest** [AdrienPoupa/AttestationDeplacement#56]
Ça serait super que l'app garde en mémoire la derniere case cochée  (comme elle le fait pour les autres infos), ou alors d'enregistrer une/des case cochée par défaut.

(Comme ça il suffit d'appuyer sur `+`, et hop roule bouboule)

ps: Merci beaucoup pour ton app Adrien !

**Comment by Yanonix** [comment]
Pour un entre deux, mettre les cases à cocher pour le motif en haut plutôt qu'en bas. Ça permettrait d'éviter un geste, celui de scroller.

**Comment by Otiel** [comment]
> Pour un entre deux, mettre les cases à cocher pour le motif en haut plutôt qu'en bas. Ça permettrait d'éviter un geste, celui de scroller.

Il faut que le bouton "Générer" devienne toujours visible dans ce cas-là.

**Comment by okpapt** [comment]
Des demandes en ce sens, meilleure ergonomie, déjà faites au Printemps, mais Adrien Poupa veut rester fidèle au site officiel.

**Comment by WiliTest** [comment]
C'est dans la derniere update (l'app se souvient maintenant de la case!) Merci beaucoup!
