### ISSUE TITLE
Option "Achats de première nécessité" manquante

### ISSUE THREAD

**Issue by Deuchnord** [AdrienPoupa/AttestationDeplacement#57]
Il manque une option pour les achats de première nécessité dans le formulaire et dans le PDF.

![Screenshot_20201031-191448.jpg](https://user-images.githubusercontent.com/7600265/97786696-af57ef80-1bad-11eb-8499-c8d9e49180d9.jpg)

**Comment by cayenne17** [comment]
Bonsoir,
être vous bien en dernière version (3.0.1) ?
moi j'ai Achats comme choix
![Screenshot_20201031-215109](https://user-images.githubusercontent.com/47927025/97789795-9823fc80-1bc3-11eb-9df9-16305516bd4f.jpg)

**Comment by Typhlos** [comment]
Si l'application a été installée depuis F-Droid, c'est la version 2.0.0 qui est proposée et il n'y a effectivement pas le choix pour les achats. Après j'imagine que la dernière version devrait bientôt arriver sur F-Droid ?

**Comment by AdrienPoupa** [comment]
Oui, elle arrivera
