### ISSUE TITLE
Ajout d'un motif de deplacement

### ISSUE THREAD

**Issue by Cryptogirl** [AdrienPoupa/AttestationDeplacement#58]
Bonjour et merci pour cet application.

Serait il possible d'ajouter le motif correspondant à "Déplacements brefs, dans la limite d'une heure quotidienne et dans un rayon maximal d'un kilomètre autour du domicile, liés soit à l'activité physique individuelle des personnes, à l'exclusion de toute pratique sportive collective et de toute proximité avec d'autres personnes, soit à la promenade avec les seules personnes regroupées dans un même domicile, soit aux besoins des animaux de compagnie ;" ?

**Comment by DrJyde** [comment]
Avez vous la dernière version disponible ? 
Ce motif de déplacement est disponible sous "Sports et animaux de compagnies"

![20201101_115239.jpg](https://user-images.githubusercontent.com/73664559/97800878-0951c700-1c39-11eb-8138-77b7543ce289.jpg)
![Screenshot_20201101-115505_Attestation de dplacement.jpg](https://user-images.githubusercontent.com/73664559/97800887-18d11000-1c39-11eb-93b2-53bfdb30f21b.jpg)

**Comment by DrJyde** [comment]
Ce motif est disponible sous "Sports et animaux de compagnies"

![Screenshot_20201101-115602_Attestation de dplacement.jpg](https://user-images.githubusercontent.com/73664559/97800930-50d85300-1c39-11eb-9455-0bf5a6cec670.jpg)
![Screenshot_20201101-115505_Attestation de dplacement.jpg](https://user-images.githubusercontent.com/73664559/97800931-53d34380-1c39-11eb-9707-2d22170d139f.jpg)
