### ISSUE TITLE
feature request: générer plusieurs attestations avec des noms différents (pour sortir avec ses enfants)

### ISSUE THREAD

**Issue by tifriis208** [AdrienPoupa/AttestationDeplacement#59]
Bonjour,

Pour commencer, merci pour cette application :) Serait-il possible de saisir plusieurs personnes dans l'application pour générer plusieurs attestations ? Ça pourrait servir aux personnes ayant par exemple un enfant n'ayant pas de smartphone. 
Aujourd'hui, il est nécessaire de ressaisir chaque information (parent puis enfant) à chaque fois, l'idée serait de pouvoir sauvegarder 2 profils.

**Comment by okpapt** [comment]
Demande de profils (couple, parent-enfant) sur le même tel déjà faite au Printemps, , mais aucune évolution en ce sens, peut-être que cette fois ci sera la bonne !

**Comment by ldmpub** [comment]
C'est sûr que ce serait un plus mais c'est certainement pas mal de boulot y compris d'ergo avec impact sur les utilisateurs "habitués" qui vont peut-être trouver ça plus complexe.

Le top serait d'avoir 2 modes : 1 mode "mono-utilisateur" et 1 mode "multi-profils" avec l'ajout d'un menu Préférences à l'application.

**Comment by AdrienPoupa** [comment]
Disponible en 3.3.0! Merci a @flopal pour sa contribution
