### ISSUE TITLE
Feature request: Générer le QR Code qui permet d'etre scanné par la police directement sur le smartphone

### ISSUE THREAD

**Issue by Banane84** [AdrienPoupa/AttestationDeplacement#60]
Bonjour, pensez-vous qu'il es possible d'insérer le qrcode qui a l'air assez simple on dirait juste un code texte, sans numéro ou cryptage...

Il y a le code source de génération d'atestation utilisé par le gouvernement ici
[Github](https://github.com/LABa-MI/deplacement-covid-19)

**Comment by AdrienPoupa** [comment]
C'est déjà le cas, il est visible depuis le document PDF généré ou en appuyant sur la liste dans l'écran principal
