### ISSUE TITLE
Manque l'exposant 2 dans le pdf généré 

### ISSUE THREAD

**Issue by ludoz** [AdrienPoupa/AttestationDeplacement#61]
Bonjour,

Tout d'abord félicitations pour cette appli et un grand merci ;-)

Pour rendre l'attestation similaire à "l'officielle", il faudrait rajouter l'exposant 2 à cette phrase =

"déplacements professionnels ne pouvant 
être différés(rajouter ici exposant 2)"

L'exposant 1 et 3 sont présents mais il manque le 2 qui correspond à "A utiliser par les travailleurs non-salariés, lorsqu'ils ne peuvent disposer d'un justificatif de déplacement établi par leur 
employeur."

Merci d'avance.

**Comment by AdrienPoupa** [comment]
Merci, c'est réglé dans la 3.1.0 !
