### ISSUE TITLE
Évolution

### ISSUE THREAD

**Issue by Wassingue** [AdrienPoupa/AttestationDeplacement#62]
Bonjour,

Ben déjà, merci beaucoup pour le taf !

Alors voilà, je voulais juste faire une petite proposition d'évolution de l'appli (probablement déjà demandée, mais bon, une de plus dans ce cas).
Je souhaiterais, si c'est faisable, que l'on puisse insérer en option un GIF de notre signature avec transparence du fond en lieu et place des nom et prénom dans le champ "signature".
L'attestation n'en serait que plus authentique et sa validité renforcée, voire même, devenir officielle (on peut rêver).
C'était ma petite pierre...

Bien cordialement,

Franck

**Comment by repsorp** [comment]
Cette attestation de déplacement numérique est [destinée à être scannée](https://www.phonandroid.com/attestation-deplacement-smartphone-comment-fonctionne-generateur-code.html) (QR Code)

Le QR Code généré par [l'attestation officielle](https://media.interieur.gouv.fr/deplacement-covid-19/) ne comporte pas le champ 'Signature'

[Un échange à ce sujet ici...](https://github.com/LAB-MI/attestation-deplacement-derogatoire-q4-2020/issues/67)
