### ISSUE TITLE
PDF: En application du décret n°2020-1310 du 29 octobre 2020...

### ISSUE THREAD

**Issue by Yanonix** [AdrienPoupa/AttestationDeplacement#63]
Top pour cette application.
Serait-il possible à la génération du PDF d'avoir exactement le même PDF que la version officiel ? Tout du moins en terme de texte avec le numéro du décret et sa date. Je pense que ça peut jouer en cas de contrôle via le PDF.

**Comment by AdrienPoupa** [comment]
Merci, c'est réglé dans la 3.1.0 !
