### ISSUE TITLE
Option pour modifier la date de creation de l'attestation dans le QR code

### ISSUE THREAD

**Issue by gwenvador** [AdrienPoupa/AttestationDeplacement#64]
Quand on génère une nouvelle attestation le QR code indique la date de création quand l'attestation a été faite. Si l'heure de sortie et la date de création est différente cela pourrait poser un problème lors d'une vérification. Il serait bien d'avoir une option pour modifier la date de création ou avoir les deux dates identiques.

**Comment by okpapt** [comment]
tu peux créer une attestation à 20h00 pour t'en servir à 7h00 le lendemain, non ?

**Comment by gwenvador** [comment]
Le soucis c'est si tu anti-dates l'attestation c'est visible sur le QR code avec la date de création. Par exemple dans le cas où tu as oublié de la faire avant de partir.

**Comment by BP22190** [comment]
Ce comportement est celui de l'application officielle.

Mais c'est vrai que ce serait un plus de pouvoir indiquer la date de création que l'on veut...

**Comment by ldmpub** [comment]
Je pense qu'il faut que l'application respecte strictement les contraintes officielles sinon c'est la porte ouverte à des "hacks" induisant d'office une perte de confiance dans l'appli pour les utilisateurs => et de fait un moindre succès.

**Comment by BP22190** [comment]
Oui et non...

Je n'aurais pas du moi-même écrire "application officielle" : la seule chose officielle est le document papier qu'on est censé porter avec soi. Ce document ne comporte qu'une date et heure, celle du début de sortie.

La datation du moment de rédaction n'a été introduite que dans l'application Internet, et si je lis le code source disponible ici sur GitHub, il a été produit par un codeur indépendant (il a mis son nom en copyright en plus de la référence au Ministère de l'Intérieur, ce que ne ferait pas un fonctionnaire du ministère, un fonctionnaire ne peut revendiquer un copyright individuel pour un travail réalisé au titre de son travail d'agent de l'Etat). Comme cette information lisible uniquement dans le QRcode ne figure pas sur le document papier, on peut supposer qu'elle n'a rien d'uen contrainte officielle, mais est seulement une initiative du développeur. Quant à l'application utilisée les policiers, elle n'est qu'un lecteur de QRcode, l'interprétation est visuelle sans analyse sémantique automatique du contenu par l'application autant que je sache.
Dans la pratique, il est tout à fait possible de prédater ou postdater le document papier, donc, pourquoi pas le QRcode !

PS: accessoirement, cette application en ligne est tellement buguée que faire la part entre ce qui serait "officiel", et ce qui serait "fortuit" est assez hasardeux, sauf à avoir le document de cahier des charges devant les yeux !

**Comment by ldmpub** [comment]
Ok tu m'as convaincu de la "légitimité" et de l'intérêt de ta demande.

Reste à savoir si techniquement il est facile d'anti-dater / post-dater le timeStamp de génération (par exemple il faut que ce timeStamp soit un attribut différent de la date "système" de modif / génération du fichier PDF qui est automatique et j’imagine non-modifiable via le SDK Android).

**Comment by BP22190** [comment]
Est-ce qu'il ne suffirait pas d'ajouter un champ similaire au champ horaire, prérempli avec l'heure courante également, et éditable. Et dans le document produit, utiliser cette horaire plutôt que la date courante système ?

Concernant le document papier "officiel", c'est de toute façon une anomalie que celui-ci ne propose qu'une date avec une formulation ambigue : il est écrit : "fait le: ... à : ...", qui laisse supposer qu'il faut écrire la date de rédaction, comme sur un chèque par exemple, mais en dessous, il est dit "indiquez la date et heure de sortie", ce qui ne veut pas dire la même chose !
Ces attestations sont aussi incohérentes que la communication du gouvernement en ce moment...

A noter d'ailleurs que l'attestation générée par l'application du site du ministère est, dans sa version papier, devenue différente dans la présentation de celle à imprimer soit même qui a été changée le 30 oct. (avec cependant le même contenu).

**Comment by okpapt** [comment]
@gwenvador > 
> 
> Le soucis c'est si tu anti-dates l'attestation c'est visible sur le QR code avec la date de création. Par exemple dans le cas où tu as oublié de la faire avant de partir.

Tu peux toujours changer la date/heure système de ton tel pour générer ton QRcode ...


@BP22190 > 
> Concernant le document papier "officiel", c'est de toute façon une anomalie que celui-ci ne propose qu'une date avec une formulation ambigue : il est écrit : "fait le: ... à : ...", qui laisse supposer qu'il faut écrire la date de rédaction, comme sur un chèque par exemple, mais en dessous, il est dit "indiquez la date et heure de sortie", ce qui ne veut pas dire la même chose !
> 
il n'y a rien d’ambiguë, voir plus haut : https://github.com/AdrienPoupa/AttestationDeplacement/issues/64#issuecomment-720413702

**Comment by BP22190** [comment]
> Tu peux toujours changer la date/heure système de ton tel pour générer ton QRcode ...

Le but de cette appli, c'est de se faciliter la vie et aller vite non ?

**Comment by okpapt** [comment]
J'ai quand même un doute sur la réelle nécessité de générer systématiquement  automatiquement une attestation antidatée.
Si tu as exceptionnellement oublié de la faire avant de partir, une rapide manipulation système de la date est une solution simple à mettre en pratique.
Générer automatiquement une attestation antidatée juste avant un contrôle des forces de l'ordre, c'est une autre approche dont je ne commenterai pas d'avantage la finalité.
