### ISSUE TITLE
App non installé

### ISSUE THREAD

**Issue by ghost** [AdrienPoupa/AttestationDeplacement#66]
Bonjour,
lorsque on veut installer une mise à jour de l'app , on a un message : `package conflits`
Il faut désinstaller donc on perd les infos qu'on a entrés , bon c pas grand chose non plus .

**Comment by AdrienPoupa** [comment]
C'est probablement car tu as plusieurs versions installées pour le même nom de package (fdroid, apk auto signé, Play store). Installer une version par dessus une autre d'origine différente peut déclencher ce message. Je te suggère de garder une seule source ou de désinstaller l'application avant de la réinstaller d'une autre source.
