### ISSUE TITLE
PDF non « signé »

### ISSUE THREAD

**Issue by Aboulafia666** [AdrienPoupa/AttestationDeplacement#67]
Depuis la version 3.1.0 la signature avec le prénom et le nom n'apparaît plus en bas du PDF généré.

En tous cas, merci beaucoup pour cette application très pratique.

**Comment by LucasBourgeois** [comment]
https://github.com/AdrienPoupa/AttestationDeplacement/issues/62

Le Qr code est considéré comme une signature numérique.
Du coup le champs signature n'est plus utile, tu peux close ton issue :)

**Comment by Aboulafia666** [comment]
Voir : https://github.com/LAB-MI/attestation-deplacement-derogatoire-q4-2020/issues/67

**Comment by AdrienPoupa** [comment]
J'ai fait le choix de ne plus remplir le champ signature étant donné que le générateur officiel ne le fait pas. Je veux rester aussi proche que possible de ce dernier. Je la remettrai s'ils changent d'avis.

**Comment by AdrienPoupa** [comment]
Réponse officielle ici https://github.com/LAB-MI/attestation-deplacement-derogatoire-q4-2020/issues/67#issuecomment-720544781
