### ISSUE TITLE
PDF ou ça ?

### ISSUE THREAD

**Issue by BP22190** [AdrienPoupa/AttestationDeplacement#68]
Je n'arrive pas à trouver où les pdf's des attestations sont stockés sur le téléphone ?
Dans quel répertoire ?
Si on efface le cache et les données de l'application, ils sont toujours là, mais où... ?

**Comment by AdrienPoupa** [comment]
Ils sont dans le répertoire de l'application, dans le dossier data. Cette façon de faire permet de ne demander aucune permission a l'installation de l'application. Ce dossier devrait être supprimé lors de la désinstallation de l'application. L'option partager permet de sauvegarder le fichier ailleurs.
