### ISSUE TITLE
crash de l'application quand on ne renseigne pas l'heure

### ISSUE THREAD

**Issue by bikepunk** [AdrienPoupa/AttestationDeplacement#69]
Quand on ne renseigne pas l'heure, et qu'on fait "Générer", ça crashe.
version 3.0.1 dans LineageOS 16.0

**Comment by ldmpub** [comment]
OK mais c'est un cas limite peu courant car pas très logique => à mon avis cette correction n'est pas prioritaire.

Selon moi, la meilleure solution serait simplement de rendre l'heure obligatoire (contrôler qu'elle n'est pas vide).
