### ISSUE TITLE
Icônes invisibles avec thème noir

### ISSUE THREAD

**Issue by bohwaz** [AdrienPoupa/AttestationDeplacement#7]
J'ai un thème noir (AMOLED) et dans la liste des attestations on ne voit pas les icônes PDF/supprimer (qui doivent être en noir sur fond noir j'imagine ?). Mais en cliquant un peu au hasard on arrive à faire les actions.

**Comment by AdrienPoupa** [comment]
Les icones sont noires sur fond blanc. Sais-tu si on peut détecter la présence d'un thème amoled? Je n'ai rien trouvé de probant sur StackOverflow

**Comment by bohwaz** [comment]
A mon avis il faut leur mettre un fond blanc, ça règlerait le souci ?

**Comment by AdrienPoupa** [comment]
Le truc c'est que le fond est blanc dans l'appli. Donc il faudrait détecter si un thème amoled est utilisé pour changer l'image en blanc seulement dans ce cas mais je ne ne sais pas comment ça peut se détecter

**Comment by bohwaz** [comment]
Je me demande si c'est pas un truc de ce genre-là : https://stackoverflow.com/questions/28605031/androidattr-selectableitembackground-not-visible-enough-on-a-dark-background ?

ou alors le fait que tu ai mis null comme background ? tu a essayé avec `android:background="@android:color/transparent` ? Je me demande si c'est pas géré automatiquement ensuite par Android (mais aucune idée en fait :D )

**Comment by AdrienPoupa** [comment]
Réglé en 1.2.0 :)

https://github.com/AdrienPoupa/AttestationDeplacement/releases/download/1.2.0/app-release.apk

L'application est désormais aussi disponible sur le Play Store: https://play.google.com/store/apps/details?id=com.poupa.attestationdeplacement
