### ISSUE TITLE
Appli TousAntiCovid 2.1.0

### ISSUE THREAD

**Issue by repsorp** [AdrienPoupa/AttestationDeplacement#70]
Bonjour à tous,

l'appli [TousAntiCovid 2.1.0](https://play.google.com/store/apps/details?id=fr.gouv.android.stopcovid&hl=fr) permet maintenant de [générer également une attestation](https://www.numerama.com/tech/663064-lattestation-de-deplacement-est-maintenant-disponible-sur-tousanticovid.html).

Cela n'enlève absolument rien à l'utilité de l'application FOSS d'Adrien.

Je joins quelques screenshots issus de TousAntiCovid pour faire en sorte, si Adrien le décide bien évidemment, de maintenir une ressemblance au niveau du visuel des codes QR afin d'éviter d'éventuels désagréments en cas de contrôle.

Pour info TousAntiCovid ne comporte même plus l'attestation elle-même (celle qu'on peut imprimer) mais uniquement le code QR.

L'appli permet de générer plusieurs Attestations/QR dont les dates & heures apparaissent juste en dessous du code QR:

![3](https://user-images.githubusercontent.com/6297032/97923355-2207cd00-1d5e-11eb-8957-1b0949bca3fa.jpeg)
![2](https://user-images.githubusercontent.com/6297032/97923363-23d19080-1d5e-11eb-9bce-709fac2ffe5f.jpeg)
![1](https://user-images.githubusercontent.com/6297032/97923367-246a2700-1d5e-11eb-9c18-fc7bfed6505c.jpeg)

**Comment by repsorp** [comment]
Quelques [précisions sur l'authenticité](https://www.numerama.com/politique/661907-confinement-comment-telecharger-et-utiliser-lattestation-de-deplacement.html) du document qui ne tient pas encore compte de l'application TousAntiCovid:

`Pour garantir l’authenticité du document, il s’agit d’un formulaire à remplir sur le site du gouvernement et nulle part ailleurs. Une fois rempli, il est horodaté et génère un QR Code, pouvant être scanné. D’après ce que l’on avait déjà pu constater en avril lors du confinement, le formulaire est exécuté en local dans le navigateur et ne transmet pas d’information sur les serveurs du gouvernement — c’est ce que le ministère avait promis. La version couvre-feu de l’attestation semble être la même avec des champs différents pour les motifs. Les champs du formulaire ne sont pas des sélecteurs, ce qui signifie que vous pouvez faire des erreurs — par exemple sur les dates. Il faudra donc bien vérifier que toutes les informations sont exactes !`

**Comment by repsorp** [comment]
Alors que l'application TousAntiCovid donne depuis ce matin la possibilité de générer ses propres attestations de déplacement, il semblerait que les QR codes créés ne soient pas reconnus comme valides par les appareils de la police. Pour l'heure, le problème concerne uniquement les smartphones sous Android. Il pourrait être lié au format des dates sur l'attestation différent de celui attendu par le lecteur.
https://www.phonandroid.com/tousanticovid-le-qr-code-genere-pour-lattestation-de-deplacement-nest-pas-valide.html

**Comment by AdrienPoupa** [comment]
A ma connaissance les QR codes générés ici sont strictement identiques à ceux du formulaire officiel.
