### ISSUE TITLE
Rapport Defensive Lab Agency -

### ISSUE THREAD

**Issue by arochedy** [AdrienPoupa/AttestationDeplacement#71]
Bonjour, 

Déjà : super appli hyper pratique merci ;)

J'ai juste une question concernant le Rapport Defensive Lab Agency (https://forensic.defensive-lab.agency/covid/reports/4c5136979e951032607bd89c1ed0c828a644d46917b1814d526f02821a20b745/)

Dans le readme y'a ecrit 

`L'application ne demande aucune autorisation : elle ne peut donc pas communiquer sur internet, donc ne peut pas envoyer de données où que ce soit. C'est à ma connaissance la seule application mobile open source et sans publicités. Même la Defensive Lab Agency le dit dans son rapport !`

Mais dans le rapport on a : 

`The application probably sends data over HTTP/S.`
et 
`The application probably gets the location based on GPS and/or Wi-Fi.`

Je comprend pas trop leur rapport : ils arrivent pas à être sûr que l'app utilise pas HTTPS et la localisation ?

**Comment by AdrienPoupa** [comment]
Il n'y a pas de géolocalisation ni de communication internet, les permissions ne sont pas demandées.
