### ISSUE TITLE
Feature - rendre le QR code optionel

### ISSUE THREAD

**Issue by Candidesk8** [AdrienPoupa/AttestationDeplacement#72]
L'objet du QR code est de faciliter la saisie des policiers : il ne contient que les informations que l'utilisateur a lui même renseigné.Ainsi la saisie est réalisé par l'usager, les forces de l'ordre ne font que valider les saisie comme conforme aux documents officiels. Ceci permet de faciliter le fichage dans gendNotes avec notamment des informations telles que : origine raciale ou ethnique, opinions politiques, philosophiques ou religieuses, appartenance syndicale, santé ou vie sexuelle ou l'orientation sexuelle.

Est-il possible d'avoir une option qui permette de générer un PDF sans QRCode ?

**Comment by AdrienPoupa** [comment]
Bonjour,

Non, le but est de générer un document aussi similaire que possible du générateur officiel.

**Comment by maximebochon** [comment]
@Candidesk8
À titre d'information, le QR-Code fournit, en plus des informations renseignées par l'utilisateur, un horodatage de création du document (relativement à l'horloge de l'utilisateur).
