### ISSUE TITLE
Affichage de la signature

### ISSUE THREAD

**Issue by bigboss11100** [AdrienPoupa/AttestationDeplacement#74]
Nom et Prénom ont disparu a côté de la signature sur la version 3.1
Pouvez vous apporter la correction.
Merci

Cordialement

**Comment by AdrienPoupa** [comment]
Le générateur officiel n'insère pas la signature, donc je ne l'ai pas mise: https://github.com/AdrienPoupa/AttestationDeplacement/issues/67
