### ISSUE TITLE
Feature request : permettre d'ajouter un widget pour générer une attestation en un seul clic 

### ISSUE THREAD

**Issue by mledoze** [AdrienPoupa/AttestationDeplacement#75]
L'idée serait de permettre d'ajouter un widget paramétré avec le motif de déplacement, pour pouvoir générer une attestation en un seul clic.

Les informations personnelles doivent être préalablement enregistrées dans l'application pour que cela fonctionne. 

L'attestation serait générée automatiquement avec la date et l'heure courante. 

Merci.

**Comment by ldmpub** [comment]
Ok et comment imagines-tu retrouver l'attestation en cas de contrôle ?

**Comment by mledoze** [comment]
Là où elles sont présentées actuellement, c'est-à-dire dans l'application.

**Comment by AdrienPoupa** [comment]
C'est une bonne idée, si jamais tu peux l'implémenter j'acceptera ta PR avec joie

**Comment by mledoze** [comment]
Je pourrai dans l'absolu, mais je préfère passer mon tour parce que 1/ ça fait trop longtemps que je n'ai pas fait de dev Android et 2/ je n'ai pas assez de temps en ce moment ^^

**Comment by AdrienPoupa** [comment]
Je ferme car je n'aurai pas le temps de l'implémenter, mais si quelqu'un peut en faire une PR je regarderai.
