### ISSUE TITLE
Générer exactement le même PDF que celui du MI

### ISSUE THREAD

**Issue by bohwaz** [AdrienPoupa/AttestationDeplacement#8]
Le PDF actuellement généré n'est pas identique à celui généré par le site du ministère de l'intérieur, il lui manque le QR code en petit en bas de la page 1 (avec la date de création du code juste en dessous) et la page 2 avec le QR code en grand.

Dans un souci de cohérence ça serait bien de générer un PDF identique, histoire d'éviter les discussions avec les FO.

**Comment by AdrienPoupa** [comment]
Fait en 1.1.0: https://github.com/AdrienPoupa/AttestationCoronavirus/releases/download/1.1.0/app-release.apk
