### ISSUE TITLE
Permettre de renouveler une attestation

### ISSUE THREAD

**Issue by wincelau** [AdrienPoupa/AttestationDeplacement#80]
Dans le listing des attestations déjà générées ajouter une action "Renouveler" qui crééra une nouvelle attestation avec le même motif mais à l'heure actuelle.

Ceci permettra de pouvoir générer une attestation en un "clique".

**Comment by AdrienPoupa** [comment]
Bonjour,

Je ne pense pas que ce soit nécessaire étant donné que tout est gardé en mémoire. Il suffit de 2 taps, + et Générer pour refaire une attestation identique à la précédente.

**Comment by wincelau** [comment]
Oui c'est vrai que de 2 taps c'est pas non plus handicapant. Je pense que c'est le fait d'être obligé de scroller tout en bas et de devoir recocher la même case qui m'a inspiré cette issue.
