### ISSUE TITLE
Feature request: date de sortie affichée

### ISSUE THREAD

**Issue by Iey4iej3** [AdrienPoupa/AttestationDeplacement#87]
J'ai enregistré un déplacement pour un examen dans une semaine. Je vois que maintenant la seule date affichée est la date de création. Je veux que soit aussi affichée la date de sortie pour mieux savoir quelle attestation dois-je afficher lors d'un contrôle.

**Comment by piotrcki** [comment]
J'approuve cette requête et je partage le même besoin.

De plus, ce qui est demandé pour la date devrait aussi être fait pour l'heure de sortie.

Il y a peut-être un rapprochement à faire avec #65 .

**Comment by AdrienPoupa** [comment]
Fait :) https://github.com/AdrienPoupa/AttestationDeplacement/commit/4089fab5fa71d339b4c8c5bd9093849272d92161
