### ISSUE TITLE
[suggestion] Générer une attestation dès l'ouverture de l'appli

### ISSUE THREAD

**Issue by Shohreh** [AdrienPoupa/AttestationDeplacement#88]
En utilisant les paramètres par défaut.

Pratique quand on doit montrer l'attestation aux forces de l'ordre alors que, au choix, on a oublié d'en générer une en sortant ou qu'on a dépassé son heure de sortie légale pour prendre l'air.

À mettre en option pour ceux qui ont des scrupules.

**Comment by AdrienPoupa** [comment]
Bonjour,

Je ne pense pas que ce soit nécessaire étant donné que tout est gardé en mémoire. Il suffit de 2 taps, + et Générer pour refaire une attestation identique à la précédente.
