### ISSUE TITLE
Error Correction Level n'est pas celui de l'app "officielle"

### ISSUE THREAD

**Issue by BP22190** [AdrienPoupa/AttestationDeplacement#92]
Je viens de me rendre compte que le QR Code généré n'a pas le même niveau d'Error Correction Level que celui du QR Code généré par l'application en ligne du Ministère : celui du Ministère semble avoir un ECL niveau M (15%), et celui généré par cette application un ECL niveau L (7%).
Ça se remarque en comparant ne serait-ce que le nombre de pixel de chacun.
Bien entendu, le résultat lu est le même, mais cela permet de savoir qu'il a été fabriqué avec une application "non officielle".
A noter également la taille du QR Code sur la page un en bas à droite, trop petit.

**Comment by okpapt** [comment]
Il me semble qu'il est possible de recopier manuellement le formulaire.
Si tu as le temps, tu peux donc aussi dessiner le qrcode...
:-))
Sauf erreur de ma part :
- il n'y a aucune obligation d'utiliser l'application officielle.
- il n'y a aucune interdiction d'utiliser une application tierce.

**Comment by BP22190** [comment]
En fait, je voulais surtout dire que l'ECL est plus faible que celui utilisé par le Ministère, et qu'il y aurait un risque (faible) de moindre reconnaissance du QR code par les applications de agents de contrôles.
Mais ce risque doit être très très faible avec un QR code affiché sur un écran (sauf écran cassé...), cette redondance est surtout utile pour les QR code affichés sur des supports de moindre qualité visuelle.
