### ISSUE TITLE
Impossible d'avoir plusieurs profils avec le même nom et une adresse différente

### ISSUE THREAD

**Issue by vulonkaaz** [AdrienPoupa/AttestationDeplacement#96]
Souvent quand je squatte chez des potes je remplis mon attestation en utilisant leur adresse à eux au lieu de ma propre adresse (pour des raisons évidentes de type: je vais avoir l'air bien con si le flic qui me contrôle voit que je fait mes courses à 60km de chez moi)

Or le problème c'est que si je met mon nom avec une adresse différente de d'habitude ça MODIFIE mon profil au lieu d'en créer un nouveau et je doit retaper mon adresse à chaque fois que je "déménage"

Comment suis-je censé frauder efficacement le confinement si on me met des bâtons dans les roues de cette sorte ?

**Comment by BP22190** [comment]
Sans doute que l'objet de cette application n'est pas de fournir un outil pour frauder, mais juste pour se faciliter la vie ?
