### ISSUE TITLE
Nouvelle version pour déconfinement ? 

### ISSUE THREAD

**Issue by Elvis25S** [AdrienPoupa/AttestationDeplacement#98]
Salut, à quand la nouvelle version avec les commentaires à jour pour le 29 novembre 2020 ?
Merci !

**Comment by okpapt** [comment]
certainement le 28 au soir...

**Comment by dbenchi** [comment]
Can you please release the new version of the attestation?

**Comment by okpapt** [comment]
A voir la rapidité de réaction d'Adrien Poupa pour les précédentes versions et améliorations, je pense qu'il fera son maximum pour nous satisfaire, et que s'il traine un peu, c'est qu'il doit avoir un sérieux contre-temps.
Pour les impatient(e)s il y a l'app "officielle" qui est à jour.
L'esprit "je veux et j'exige" n'a pas lieu d'être pour une appli gratuite, sans pub et sans utilisation de données perso.

**Comment by lagirl30** [comment]
Je comprends pas trop les personnes qui prennent le temps d'ouvrir un ticket sur github pour demander quand sera mise à jour l'Appli, plutôt que de perdre 5 minutes pour ça, utiliser donc la version numérique dispo sur le site du gouvernement en attendant, ça tue personne...

Entre les demandes ici, et le harcèlement sur les commentaires du play store, c'est à cause de gens comme vous avec une impatience exacerbée que les dev comme Adrien Poupa abandonnent leurs projets...

l'esprit de l'open source n'est pas "du tout cuit quand vous l'exigez" pour ça y a les applis payantes ou blindées de pubs qui vous voleront vos données en échange d'un SERVICE...

**Comment by AdrienPoupa** [comment]
Je m'en occupe aujourd'hui :)

**Comment by GreenBlood** [comment]
Je rajoute du bruit dans ce ticket mais, à l'attention des deux autres utilisateurs qui disent qu'exiger quelque chose d'un logiciel libre c'est naze, et que ça décourage les dev : 

Certes, mais il faut prendre en compte aussi le public auquel s'adresse cette application, combien parmi tout les utilisateurs réguliers sont des gens au fait de ce qu'es le libre, l'open source, github, les tickets ? Je pense pas des masses, vu l'application. Donc je vois pas vraiment l'intérêt d'être aggressif avec des néophytes qui ne sont pas nécessairement au courant des us et coutume du milieu, vous ne découragez peut être pas un dev, mais vous contribuez à cette image d'elitisme du logiciel libre, et vous découragez peut être un novice qui aurait pu contribuer par ailleurs. 

Merci encore à Adrien Poupa pour son logiciel, néanmoins :)

**Comment by lagirl30** [comment]
@GreenBlood Un novice qui vient ouvrir un ticket sur github ? Alors que github est inconnu des novices ? C'est une blague ou c'est sérieux ?

Ceux qui couinent sans cesse que l'application n'est pas à jour en temps et en heure, sont des râleurs nés, le bobo français typique !

On a les mêmes sur Linux, ceux qui vont hurler parce que la dernière version de systemd a un jour de retard sur leurs distributions favorites !

Il y a les sources, alors faites-la vous même, vous l'aurez en temps et en heure comme désiré ;)

Et si ça vous bloque de pas avoir la dernière version, il y a toujours le site officiel du gouvernement, mais c'est plus long, plus chiant à remplir, donc plus fatiguant et vous allez encore couiner ;)

M'enfin vous faîtes bien rire, on vous donne du tout cuit, au lieu d'être patient, ça réclame ici, sur les commentaires du play store !
Chacun à une vie à ce que je sache, et être développeur ne signifie pas être votre chien qui répond à vos attentes dans la seconde.
C'est taille de fou ça....

**Comment by AdrienPoupa** [comment]
https://github.com/AdrienPoupa/AttestationDeplacement/releases/tag/3.4.0 :)

**Comment by Elvis25S** [comment]
Merci Adrien pour la version mise à jour.

Et sachez que je tiens pour stupides les commentaires faits par d'autres et
que je n'exigeais rien pour ma part.

Encore merci...

**Comment by pl6025** [comment]
Bonjour,
Juste pour signaler que la version 3.4.0 est bien disponible sur le play store de google.
Mais à cette heure elle n'est malheureusement pas encore disponible sur F-Droid.
Ne sachant pas trop comment se passe les approbation sur les "stores" je voulais juste savoir si c'est une question de temps côté F-droid ou tout simplement un oubli (je penche pour la 1ere hypothèse).
[Edit] et merci pour ce boulot !
